UKHomeOffice/nmsw-ui

src/AppRouter.jsx, src/constants/AppUrlConstants.js, src/layout/Footer.jsx, src/layout/__tests__/Footer.test.jsx, src/pages/Footer/CookiePolicy.jsx, src/pages/Footer/__tests__/CookiePolicy.test.jsx
NMSW-35
----
----
- In the footer
- > You should see a link that says cookies
- click on the cookie link
- > You should be taken to /cookies
- > You should see a heading with cookies
----
=> NMSW-35 Create a cookie policy page

src/AppRouter.jsx, src/constants/AppUrlConstants.js, src/layout/Footer.jsx, src/layout/__tests__/Footer.test.jsx, src/pages/Footer/AccessibilityStatement.jsx, src/pages/Footer/__tests__/AccessibilityStatement.test.jsx
NMSW-19
----
GIVEN I am viewing a page
WHEN I click on the accessibility link in the footer
THEN I am shown the accessibility statement 
----
- go to the footer
- > you should see a link for Accessibility statement
- click that link
- > you should be taken to a page with a H1 of Accessibility statement for National Maritime Single Window
- there will be no other content on the page
----
=> NMSW-19 Accessibility statement

package.json
Update package.json version number
=> Update version to 0.3.0

src/App.jsx, src/App.test.jsx, src/AppRouter.jsx, src/components/DisplayForm.jsx, src/components/formFields/DetermineFieldType.jsx, src/components/formFields/InputRadio.jsx, src/constants/AppConstants.js, src/layout/CookieBanner.jsx, src/layout/__tests__/CookieBanner.test.jsx, src/pages/Regulatory/CookiePolicy.jsx, src/pages/Regulatory/__tests__/CookiePolicy.test.jsx, webpack.config.js
NMSW-126
----
Given I am viewing the cookie page
When I view the manage section
Then I am provided a form to manage my preferences
AND it should show my current preference
Given I have not selected a cookie preference
When I view the manage my preference form
Then the form should be set to no
Given I am viewing the manage preferences form
When I have previously selected Yes to analytics cookies
Then the form should be set to Yes
Given I am viewing the manage preferences form
When I have previously selected No to analytics cookies
Then the form should be set to No
Give I am viewing the manage preferences form
When I change the selected preference
And click save cookie settings
Then my new preference for analytics cookies should be saved
----
- To Test
- go to …
=> NMSW-126 Create Cookie Preference form

package-lock.json, setupTests.js, src/AppRouter.jsx, src/assets/main.scss, src/components/DisplayForm.jsx, src/components/__tests__/DisplayForm.test.jsx, src/components/formFields/DetermineFieldType.jsx, src/constants/AppConstants.js, src/pages/SignIn/SignIn.jsx, src/pages/SignIn/SignIn.test.jsx, src/utils/ScrollToElementId.js, src/utils/Validator.jsx, webpack.config.js
NMSW-30
----
GIVEN I am viewing the sign-in form
WHEN I attempt to submit the form without providing an email address or password
THEN  I am shown form level errors
GIVEN I have attempted to submit the sign in form
WHEN I have not provided an email address that has an '@' symbol in it
THEN I am shown a form level error related to you must provide a valid email address
GIVEN I have attempted to submit the sign in form
WHEN I have not provided a password that meet minimum requirements
THEN I am shown a form level error related to an invalid password
GIVEN I am viewing the error panel
WHEN I click an error link in that panel
THEN I am taken to the field with the error
----
- click start now
- > you should see the sign in form
- click submit without …
=> NMSW-30 Add validation, error handling, and error summary

src/components/DisplayForm.jsx, src/components/__tests__/DisplayForm.test.jsx, src/components/formFields/DetermineFieldType.jsx, src/components/formFields/InputText.jsx, src/components/formFields/__tests__/InputText.test.jsx, src/pages/SignIn/SignIn.jsx, src/pages/SignIn/SignIn.test.jsx
NMSW-120
----
GIVEN I am viewing the sign-in form
WHEN I attempt to submit the without providing an email address or password
THEN  I am shown field level errors
----
- click start now
- > you should see the sign in form
- click submit
- > you should see an error that the email address is invalid
- > you should see an error that the password is required
- start typing in the email field
- > you should see the error disappear
- start typing in the password field
- > you should see the error disappear
----
=> NMSW-120 Field level error messages and styling

helm/Chart.yaml, package-lock.json, package.json
=> Bump version to 0.4.0

.drone.yml
NMSW-138
----
Upgrade to Node 18
----
Cypress node18 image isn't available yet
Added comment to the commented out code to say it needs to be upgraded before we use it
=> NMSW-138 cypress version

.drone.yml, README.md, helm/Chart.yaml, package-lock.json, package.json
=> Version 0.3.1

src/AppRouter.jsx
NMSW-32
----
Given I have typed in a page url that does not exist
When I hit enter
Then I am taken to the landing page
----
- go to localhost: 3000
- try to go to /badpage
- you should be taken to the landing page
----
=> NMSW-32 Redirect to landing page on 404s

.gitignore, cypress/e2e/components/cookie.comp.js, cypress/e2e/features/cookie/cookie.feature, cypress/e2e/features/cookie/cookie.js, cypress/e2e/pages/cookie.page.js
- NMSW-126:Create Cookie Preference form
- NMSW-25: Add a confirmation of cookie preference set banner
- NMSW-27 : Create success banner for cookie page
----
```
npx cypress open 
```
then select cookie.feature to run cookie feature specs
=> Test cookie page features

cypress.config.js, cypress/e2e/components/cookie.comp.js, cypress/e2e/features/cookie/cookie.feature, cypress/e2e/pages/cookie.page.js, cypress/support/step_definitions/cookieSteps.js
Changed feature file from scenario to scenario outline format for code reusability
Added scenario to test change cookie preference in manage cookie page 
```
npx cypress open 
```
then select cookie.feature to run cookie feature specs
=> Add test to cookie banner

helm/Chart.yaml, package.json
=> Update version numbers

docs/form_creator.md, src/AppRouter.jsx, src/components/DisplayForm.jsx, src/pages/Regulatory/CookiePolicy.jsx, src/utils/ScrollToElement.js, src/utils/ScrollToTopOnNewPage.js
NMSW-33
----
Separating https://github.com/UKHomeOffice/nmsw-ui/pull/58 into multiple PRs for ease of review
This adds a scroll to h1 function in the scrollToElement (renamed from scrollToElementId)
----
- open second form
- click submit
- > page should be scrolled to the h1
- open cookie page
- click submit on form
- > page should be scrolled to the confirmation banner
- click on accessibility link in footer
- > page should be scrolled to top on load
----
=> NMSW-33 Scroll to Element

helm/Chart.yaml, package-lock.json, package.json
=> Bump version to 0.6.0

helm/Chart.yaml, package-lock.json, package.json
Update version number to 0.6.1
=> Update version number

docs/form_creator.md, docs/form_creator_example.md, src/assets/main.scss, src/components/DisplayForm.jsx, src/components/__tests__/DisplayForm.test.jsx, src/components/formFields/DetermineFieldType.jsx, src/components/formFields/InputPhoneNumber.jsx, src/components/formFields/InputRadio.jsx, src/components/formFields/__tests__/InputPhoneNumber.test.jsx, src/constants/AppConstants.js, src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/__tests__/RegisterYourDetails.test.jsx, src/utils/Validator.jsx
NMSW-155
----
Given I provided my email address CORRECTLY
AND they match
WHEN I submit them
THEN I am redirected to provide my other details:
GIVEN I have provided ALL of my details
WHEN I Submit my details
THEN I am asked to create my password
----
- run locally
- click on create account link
- enter email addresses and continue
- > you should see the Your details page
- click submit
- > all fields should error
- enter something in fullname
- enter something in company name
- enter something in JUST THE SMALL FIELD for phone number, leave the large field blank
- enter something in country
- select if a shipping agent
- click submit
- > phone number field should error
- delete value from short field and enter something in long field for phone number
- click submit
- > phone number field …
=> NMSW-155 Your details page for registration & an InputPhone component

Dockerfile, package-lock.json, package.json, src/components/__tests__/DisplayForm.test.jsx, src/constants/AppAPIConstants.js, src/constants/Config.js, src/hooks/usePostData.js, src/pages/Register/RegisterEmailAddress.jsx, src/pages/Register/__tests__/RegisterEmailAddressPost.test.jsx, src/utils/Auth.js, webpack.config.js
NMSW-155
----
Given I have provided valid answers to the register email form
When I click continue
And that email address has not yet been registered
Then I am taken to the your details page
----
- run `npm ci` to install axios
- run app
- run BE in docker locally (currently `version-0.3.0 branch` but double check)
- go to create account
- open your dev tools network tab
- enter a new email address
- confirm that in the confirmation field
- click continue
- > in the network tab you should see the POST to /registration and a success response
- > you should be taken to the your details page
- go back to the email page
- enter the same email you just submitted
- click continue
- > in the network tab you should see the POST to /registration and a 400 response
- go to console
- > you should …
=> NMSW-155 API POST hook and post email to /registration

src/components/DisplayForm.jsx, src/pages/Register/RegisterEmailAddress.jsx, src/pages/Register/RegisterEmailVerified.jsx, src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/RegisterYourPassword.jsx, src/pages/SignIn/SignIn.jsx
NMSW-155
----
Update UI styling to match prototype
----
Compare these pages to prototype
- register email address
- register your details
- register password
Width and font styles should be close to the prototype
----
RegisterEmailVerified functionality comes in the next PR, it's just landed in here as I'd created it before I did the styling updates so it's been merged in with the other pages
=> NMSW-155 styling

src/AppRouter.jsx, src/constants/AppUrlConstants.js, src/pages/Landing/Landing.jsx, src/pages/Register/RegisterEmailAddress.jsx, src/pages/Register/RegisterEmailVerified.jsx, src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/RegisterYourPassword.jsx, src/pages/Register/__tests__/RegisterEmailAddressPost.test.jsx
NMSW-155
----
Update const names to include _URL when they are a url
----
Review consts
----
=> NMSW-155 All URL consts should include _URL

src/constants/AppConstants.js, src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/__tests__/RegisterYourDetails.test.jsx, src/utils/Validator.jsx
NMSW-155
----
Add a max length condition to the validator
----
- run app
- go to http://localhost:3000/create-account/your-details (lets you bypass the email step)
- click submit
- > you should have an error that country is required
- enter a country name e.g. `Australia`
- click submit
- > you should have an error that country can only be 3 digits
- enter a 3 letter country code e.g. `AUS`
- fill out other fields
- click submit
- > form should submit
----
=> NMSW-231 Max length validator

docs/form_creator.md, src/components/__tests__/DisplayForm.test.jsx, src/components/formFields/InputPhoneNumber.jsx, src/components/formFields/__tests__/InputPhoneNumber.test.jsx, src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/__tests__/RegisterYourDetails.test.jsx
NMSW-155
----
Change `country code` to `country phone code` so that it's not confused with the country 2/3 digit codes
----
- run tests, all should pass
- review code
----
=> NMSW-232 Country phone code label

src/pages/Register/RegisterConfirmation.jsx, src/pages/Register/__tests__/RegsiterConfirmation.test.jsx
NMSW-155
----
Given I have clicked submit on the password page
When there are no errors 
And my account has been created (200 response from API)
Then I am shown the confirmation page
----
- run BE in docker
- run app
- go through the create account process and submit
- > you should be shown the confirmation page
- > it should have <your company name> is created in the panel
----
=> NMSW-235 Registration confirmation page

src/pages/TempPages/SecondPage.jsx, src/utils/__tests__/Auth.test.js
=> NMSW-236 Add tests for Auth.js

src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/__tests__/RegisterYourDetails.test.jsx
NMSW-238
----
- `Enter your Country phone code and phone number` should be `Enter your country code and phone number`
- `Enter 3 digit Country phone code` should be `Enter 3 digit country code`
----
Review code
----
=> NMSW-238 Change `Country phone code` to `country code` in error messages

cypress/e2e/features/registration.feature, cypress/e2e/pages/base.page.js, cypress/support/step_definitions/registration.steps.js
User registration feature validation
To run just the validation feature(user registration email page validation) , pls comment other scenarios 
```
npx cypress open 
```
choose registration.feature to run registration feature specs
----
=> Test to validate user registration errors

cypress/e2e/features/registration.feature, cypress/e2e/pages/registration/email.page.js, cypress/support/step_definitions/registration.steps.js
Test to validate registration error message if user already exist
----
To test
To run just the validation feature(Should not register existing user) , pls comment other scenarios
```
npx cypress open 
```
choose registration.feature to run registration feature specs
=> Test register user throws error if user already exist

src/components/DisplayForm.jsx
NMSW-196
----
Ensure heading in the cookie page has discernible text
----
- Run the app
- Go to localhost:3000
- Go to /cookies
- Run axe dev tools
- > The 'Ensures headings have discernible text' axe error should not show
----
=> NMSW-196 AXE accessibility heading issue

package-lock.json
NMSW-172
----
Update loader-utils package using 'npm audit fix'
----
- Run app
- > It should work as expected
- Run tests
- > Tests should pass
----
=> NMSW-172 Update loader-utils package

public/index.html, src/assets/css/noscript.css, webpack.config.js
NMSW-283
----
Handle no javascript with a styled page
----
- turn off javascript in browser
- refresh page
- > the 'no javascript' page should load
- turn javascript back on
- refresh page
- > the normal app should load
----
We don't have content for the page (future ticket), this ticket was a spike but as the style code is working I figure we might as well merge that part.
=> NMSW-283 Setup html in <noscript> for if user has javascript disabled

helm/Chart.yaml, package-lock.json, package.json
=> Bump version

helm/Chart.yaml, package-lock.json, package.json
=> Bump version to 0.7.0

docs/form_creator_example.md, src/AppRouter.jsx, src/components/__tests__/DisplayForm.test.jsx, src/constants/AppUrlConstants.js, src/layout/Nav.jsx, src/layout/__tests__/Nav.test.jsx, src/pages/Dashboard/Dashboard.jsx, src/pages/Landing/Landing.jsx, src/pages/SignIn/SignIn.jsx, src/pages/TempPages/SecondPage.jsx, src/pages/YourVoyages/YourVoyages.jsx
NMSW-278
----
Given I have logged in
I am landed on the /your-voyages page
With an option to 'start a new report' (button will not work)
----
- run app
- sign in
- > you should be taken to /your-voyages page
- Go though the code and check that all instances of Dashboard are changed to Your voyages
----
=> NMSW-278 Voyage details page (no voyages)

cypress/config/dev.config.js, cypress/config/local.config.js, cypress/e2e/components/cookie.comp.js, cypress/e2e/features/registration.feature, cypress/e2e/pages/registration/email.page.js, cypress/support/commands.js, cypress/support/step_definitions/registration.steps.js, cypress/support/step_definitions/sign-in.steps.js
Test added for NMSW-314
```
npm run: cypress:open:dev
```
=> Test nmsw 314

src/constants/AppUrlConstants.js
Adding TEMPLATE_PAGE_URL to TOP_LEVEL_PAGES array so that formData clears on page and back button is removed from the page
=> Add TEMPLATE_PAGE_URL to TOP_LEVEL_PAGES

src/components/__tests__/DisplayFormTests/DisplayDetailsComponent.test.jsx, src/components/formFields/DetermineFieldType.jsx, src/constants/AppAPIConstants.js, src/pages/Register/RegisterEmailCheck.jsx, src/pages/Register/RegisterEmailResend.jsx, src/pages/Register/__tests__/RegisterEmailResend.test.jsx
----
**DESIGN:**
add a 'request new email' link to check your email page (should exist) based on attached design
request a new email verification page : add the 'change where the email was sent' section based on attached design
**ACTIONS:**
Given user clicks on request a new link
When they have NOT added a new email address
And we know their registered email address
Then POST to /resend-verification-email with the stored email address
Given app has sent a POST request to /resend-verification-email
When success response received
Then show the check your email page
Given user clicks on request a new link
When they HAVE added a new email address
Then we POST to /register with the new email address
Given the app has sent a POST request to /resend-verification-link
When a 400: email address …
=> NMSW-168 Resend verification email

cypress.config.js, cypress/config/dev.config.js, cypress/config/local.config.js, cypress/e2e/features/registration.feature, cypress/e2e/pages/registration/email.page.js, cypress/fixtures/registration.json, cypress/support/commands.js, cypress/support/step_definitions/registration.steps.js, package-lock.json, package.json
Added test to cover registration feature scenarios for NMSW-180,181,182,218 and 168
Fixed failing scenarios test due to back-end change
```
npm run cypress:open:dev
```
and select registration.feature
=> Add tests with mailslurp env api

helm/Chart.yaml, package-lock.json, package.json
=> Bump to version 0.8.0

src/AppRouter.jsx, src/constants/AppUrlConstants.js, src/pages/Voyage/FileUploadConfirmation.jsx, src/pages/Voyage/ReportUploadGeneralDeclaration.jsx, src/pages/Voyage/VoyageGeneralDeclaration.jsx, src/pages/Voyage/VoyageTaskList.jsx, src/pages/Voyage/__tests__/FileUploadConfirmation.test.jsx, src/pages/Voyage/__tests__/VoyageGeneralDeclaration.test.jsx
NMSW-324
----
**Routes & links**
Page | URL | Link type | Link name | Link route | Next page
-- | -- | -- | -- | -- | --
Upload general declaration | /report-voyage/upload-general-declaration | download doc | FAL 1 general declaration | stay on page | n/a - file download
Upload general declaration | /report-voyage/upload-general-declaration | primary submit button | Check for errors | /report-voyage/general-declaration-uploaded | noErrors: General declaration uploaded
Upload general declaration | /report-voyage/upload-general-declaration | primary submit button | Check for errors | stay on page | Errors: error page
General declaration uploaded | /report-voyage/general-declaration-uploaded | primary submit button | Save and continue | /report-voyage | Draft declaration tasklist
**Design …
=> NSMW-324 General Declaration & Task List routes, GD page skeleton, File Upload page skeleton

src/AppRouter.jsx, src/constants/AppUrlConstants.js, src/pages/Voyage/VoyageCheckYourAnswers.jsx, src/pages/Voyage/VoyageTaskList.jsx, src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx, src/pages/Voyage/__tests__/VoyageTaskList.test.jsx
NMSW-324
----
prototype: /mvp-2/check-your-answers
Page | URL | Link type | Link name | Link route | Next page
-- | -- | -- | -- | -- | --
Check answers and submit | /report-voyage/check-your-answers | change link | Change | /report-voyage/upload-crew-details | Crew: upload crew details
Check answers and submit | /report-voyage/check-your-answers | change link | Change | /report-voyage/any-passenger-details | Passenger: any passenger details
Check answers and submit | /report-voyage/check-your-answers | change link | Change | /report-voyage/upload-supporting-documents | Supporting: upload supporting documents
Check answers and submit | /report-voyage/check-your-answers | download saved file | Crew.xlsx (or filename) | stay on page | na - file download
Check answers and submit | …
=> NSMW-324 Voyage check your answers routes and skeleton page

cypress/e2e/features/sign-in.feature, cypress/e2e/pages/base.page.js, cypress/e2e/pages/sign-in.page.js, cypress/fixtures/registration.json, cypress/support/commands.js, cypress/support/step_definitions/sign-in.steps.js
Added tests to verify sign-in features 
```
```
and select sign-in.feature
=> Test to verify sign-in features

src/pages/SignIn/SignIn.jsx
NMSW-360
----
- Run the app
- Go to `localhost:300/sign-in`
- Try to sign in with a valid email but an incorrect password
- > The page should scroll to the top on error
----
=> NMSW-360 Fix sign in error bug

package-lock.json, package.json, src/App.test.jsx, src/AppRouter.jsx, src/components/__tests__/DisplayFormTests/ErrorClearingErrors.test.jsx, src/components/__tests__/DisplayFormTests/ErrorPhoneNumberInput.test.jsx, src/layout/__tests__/Nav.test.jsx, webpack.config.js
NMSW-376
----
- reduce bundle size for webpack bundles
- do not have a flash of unstyled content (FOUC) when the page first loads
- increase Lighthouse performance score (> 90)
----
To test the changes:
**NO FOUC:**
- run `npm ci`
- open app
- in devtools > network tab > tick `disable cache`
- in devtools > network tab > set throttling to `slow 3G`
- refresh page
- > page will be slow to load but should load with full styling
- > page should NOT show the content without the css styling (no FOUC)
- sign in
- go to Templates page
- > you should see a loading spinner before the page loads (lazy loading)
- close browser
- open app in new browser
- in devtools > network tab > set throttling to `no throttling`
- refresh page
- > page should load quickly
- > page should NOT show the content …
=> NMSW-376 Add webpack codesplitting/bundling, miniCSSExtractPlugin & lazy load most routes

cypress/e2e/features/registration.feature, cypress/e2e/pages/base.page.js, cypress/e2e/pages/sign-in.page.js, cypress/support/commands.js, cypress/support/step_definitions/registration.steps.js, cypress/support/step_definitions/sign-in.steps.js
Updated the tests with different sign-in element locator
```
```
=> Update cypress test

.eslintrc.json, src/components/Message.jsx, src/components/__tests__/Message.test.jsx, src/constants/AppAPIConstants.js, src/constants/AppUrlConstants.js, src/pages/NavPages/YourVoyages.jsx, src/pages/NavPages/__tests__/YourVoyages.test.jsx, src/pages/Voyage/FileUploadConfirmation.jsx, src/pages/Voyage/VoyageCheckYourAnswers.jsx, src/pages/Voyage/VoyageCrew.jsx, src/pages/Voyage/VoyageDeleteDraftCheck.jsx, src/pages/Voyage/VoyageGeneralDeclaration.jsx, src/pages/Voyage/VoyagePassengerUpload.jsx, src/pages/Voyage/VoyagePassengers.jsx, src/pages/Voyage/VoyageTaskList.jsx, src/pages/Voyage/__tests__/FileUploadConfirmation.test.jsx, src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx, src/pages/Voyage/__tests__/VoyageCrew.test.jsx, src/pages/Voyage/__tests__/VoyageDeleteDraftCheck.test.jsx, src/pages/Voyage/__tests__/VoyageGeneralDeclaration.test.jsx, src/pages/Voyage/__tests__/VoyagePassengerUpload.test.jsx, src/pages/Voyage/__tests__/VoyagePassengers.test.jsx, src/pages/Voyage/__tests__/VoyageTaskList.test.jsx
NMSW-141
----
As an agent
I want to add the vessel and journey details for a declaration
**DESIGN:** https://nmsw-prototype.dev.nmsw.homeoffice.gov.uk/version-2/declarations-saved?status=false
**ACTIONS:**
Given I have logged in
I am landed on the /your-voyages page
With an option to 'start a new report'
Given I click on start a new voyage
When my auth token is still valid
Then the app POSTs to /create-voyage to begin a voyage creation
Given I click on start a new voyage
When my auth token is no longer valid
Then the app redirects me to sign in
Given the app has POSTed to /create-voyage
When an error is returned
Then the user is shown the generic error page
And the link is to 'start a new report'
Given the app has POSTed to /create-voyage
When a success is returned
Then the voyage id is …
=> NMSW-141 Create declaration ID (POST) & pass through voyage pages in flow

cypress/e2e/features/registration.feature, cypress/e2e/pages/registration/yourDetails.page.js
- change error message wording to include errors that will appear for both fields
- change the phoneNumber input to now be a diallingCode and telephoneNumber
To Test
`npx cypress open --config-file cypress/config/dev.config.js --env MAIL_API_KEY=xxx`
replace xxx with the MAIL_API_KEY
=> NMSW-392 Update Cypress tests with new phone number pattern

helm/Chart.yaml, package-lock.json, package.json
=> Bump to version 0.9.0

src/components/FileUploadForm.jsx, src/components/__tests__/FileUploadForm.test.jsx, src/constants/AppAPIConstants.js, src/constants/AppConstants.js
NMSW-268
----
Add a generic file upload component in preparation for the Declaration file uploads
----
Review and run unit/integration tests. UI use case coming in next PR
----
=> NMSW-268 Add fileupload component

docs/form_creator.md
NMSW-407
----
Update docs for autocomplete usage
----
Review docs
----
=> NMSW-407 Form Creator InputAutocomplete document updates

.eslintignore, src/utils/DownloadFile.js
NMSW-430
----
Identified issue with the linting interfering with download file
----
go to report voyage
click FAL1 download link
go to templates in nav
click each download link
All should download
----
=> NMSW-430 Add DownloadFile to eslintignore

.drone.yml
Registration tests failing, looks related to delete user step. Will fix in version-0.10.0
=> Ignore cypress tests again

helm/Chart.yaml, package-lock.json, package.json
=> Bump version to 0.11.0

cypress/config/dev.config.js, cypress/config/local.config.js, cypress/config/staging.config.js, cypress/e2e/features/fa15-upload-crew-details.feature, cypress/e2e/features/fal1-upload-general-declaration.feature, cypress/e2e/features/registration.feature, cypress/e2e/features/sign-in.feature, cypress/e2e/features/upload-supporting-documents.feature, cypress/e2e/pages/registration/yourDetails.page.js, cypress/support/step_definitions/upload-supporting-documents.steps.js
Test added to verify update error messages  NMSW-394
Run E2E test with
```
```
=> Test NMSW-394-update error messages

src/components/__tests__/MultiFileUploadStatus.test.jsx
There is a test that randomly fails which is causing the overall build to fail on occasion - added a waitFor to hopefully stop it from failing
=> Add a waitfor to hopefully stop test from randomly failing

.drone.yml
Fixing scan triggers for staging and prod
=> fix staging and prod scan triggers

.drone.yml
removing tag trigger from scan step
=> remove tag trigger from scan step

src/pages/Regulatory/CookiePolicy.jsx, src/pages/Regulatory/PrivacyNotice.jsx
NMSW-123
----
As a user 
I want to see the privacy and cookie policy
----
- Run app
- Scroll to the footer
- Click on Privacy link
- > The content should match what is in the document attached to the ticket
- > The styling should match sPCR
- Click on the Cookies link
- > The content should match what is in the document attached to the ticket
- > The styling should match sPCR
----
- There is code commented out for the tables describing cookies as there is currently no content for this (?) However it will be really easy to add in once we have details
=> NMSW-123 Content for Privacy and Cookie policy page

cypress/e2e/features/registration.feature, cypress/support/step_definitions/fal6-upload-passenger-details.steps.js
- Test added to cover NMSW-533 -Update 'do you have passengers' question to PATCH response to endpoint
- Added test to cover NMSW-290 -Update /registration POST response - notify user if account verified
```
```
select fal6-upload-passenger-details.feature
and  registration.feature
=> Test NMSW-533/NMSW-290

cypress/e2e/features/fal6-upload-passenger-details.feature, cypress/e2e/features/task-details-page.feature, cypress/e2e/pages/task.page.js, cypress/support/step_definitions/fal1-upload-general-declaration.steps.js, cypress/support/step_definitions/task-page.steps.js
Added test for NMSW-424  -Task List - show passengers as completed if declaration has passengers: no or file is uploaded
```
```
Select fal6-upload-passenger-details.feature
and task-details-page.feature
=> Test NMSW-424 

src/constants/AppConstants.js, src/pages/Regulatory/AccessibilityStatement.jsx, src/pages/Regulatory/__tests__/AccessibilityStatement.test.jsx
NMSW-124
----
----
- test links open in new window
- check the two email addresses are populated
----
=> NMSW-124 Accessibility statement

cypress.config.js, package-lock.json, package.json
Changed cypress config file to fix file template feature erroring
```
npm ci
```
to install cypress-downloadFile package as dev dependency
```
```
Select file-templates.feature
=> Fix file template test

src/components/Message.jsx, src/pages/SignIn/RequestPasswordReset.jsx, src/pages/SignIn/__tests__/RequestPasswordReset.test.jsx
NMSW-204
----
Given a user has registered but not verified their email
When they submit the forgotten password form
Then they are shown an info page asking them to verify their email
----
- register an email address
- go to sign in
- go to forgot password
- try to send a forgot password link
- > you should see the 'you need to verify page'
----
Scenario was missed from original PR
=> Password reset scenario

src/pages/Voyage/VoyageCheckYourAnswers.jsx, src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx
----
Given I am viewing a draft declaration
When I am on the check your answers page
Then I am shown no status line
And the call to action is the submit panel and button
Given I am viewing a Submitted or PreSubmitted declaration
When I am on the check your answers page
Then I am shown a submitted tag
And the call to action is a cancel button
Given I am viewing a PreCancelled or Cancelled declaration
When I am on the check your answers page
Then I am shown a cancelled tag
And there is no call to action panel
Given I am viewing a Failed declaration
When I am on the check your answers page
Then I am shown a failed tag
And there is no call to action panel
----
- go to the CYA page
- > you should NOT see a status line at the top of the voyage details
- > you SHOULD see …
=> NMSW-538 Add submitted tag and submission date (and other status tags/hidden status)

src/pages/NavPages/YourVoyages.jsx, src/pages/NavPages/__tests__/YourVoyages.test.jsx
----
**1.Display status of pre-submitted voyage**
GIVEN a voyage has JUST been submitted, but has not yet had a response from CBP
WHEN I view the voyage list
THEN the voyage is displayed as "SUBMITTED"
**2.Display status of submitted voyage**
GIVEN a voyage has been submitted AND has a success response from CBP
WHEN I view the voyage list
THEN the voyage is displayed as "SUBMITTED"
**3.Display status of pre-cancelled voyage**
GIVEN a voyage cancellation has JUST been submitted, but has not yet had a response from CBP
WHEN I view the voyage list
THEN the voyage is displayed as "CANCELLED" 
**4.Display status of cancelled voyage**
GIVEN a voyage cancellation has been submitted AND has a success response from CBP
WHEN I view the voyage list
THEN the voyage is displayed as "CANCELLED" …
=> NMSW-246 All statuses to report list

src/constants/AppAPIConstants.js, src/pages/NavPages/YourDetails/YourDetails.jsx, src/pages/NavPages/YourDetails/__tests__/YourDetails.test.jsx
NMSW-547
----
Remove change details link (not in MVP)
Remove delete account button (not in MVP)
Given I am logged in
When I go to the your details page
Then I see my email address
Then I see my full name
Then I see nothing for my company name
Then I see my phone number formatted as (xxx)xxxxxx
Then I see my country code
Then I see my type of account
Then I see nothing for company type
----
- go to your details page
- > your details should be displayed
----
Company name and type are in NMSW-551
=> NMSW-547 Display user details

src/pages/SignIn/RequestPasswordReset.jsx, src/pages/SignIn/SignIn.jsx, src/pages/SignIn/SignIn.test.jsx, src/pages/SignIn/__tests__/RequestPasswordReset.test.jsx
----
Update wording from 
```
Your email address has not been verified
You need to verify your email address to finish creating your account.
Request a new email verification link
```
To:
```
Email address not verified
We can send you a verification link so you can continue creating your account.
Send confirmation email
```
----
----
=> NSMW-203/204 Wording changes

src/pages/Voyage/VoyageCheckYourAnswers.jsx, src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx
----
If declaration is draft status show change links, otherwise don't
----
- view CYA
- > you should see draft links
- submit declaration
- go back to CYA page
- > you should not see change links
----
- cannot test Submitted, PreCancelled, Cancelled, or Failed status in UI yet without forcing the status in the code
- there is tests for these statuses
=> NMSW-538 Change links only on Draft CYA page

src/pages/NavPages/YourVoyages.jsx, src/pages/NavPages/__tests__/YourVoyages.test.jsx
----
Sort voyage list by latest first
----
- add a voyage
- add another voyage
- go back to your voyages
- > the second voyage should be at the top of the list
----
We will use Cypress tests to check the ordering of voyages
=> NMSW-600 Sort voyage list by latest first

src/constants/AppConstants.js, src/pages/Regulatory/__tests__/AccessibilityStatement.test.jsx, src/pages/Regulatory/__tests__/ContactUs.test.jsx, src/pages/Regulatory/__tests__/Help.test.jsx
NMSW-564
----
Update the NMSW support email for MVP
----
=> NMSW-564 Update support email

helm/Chart.yaml, package-lock.json, package.json
=> Bump to version-0.14.1

src/pages/Voyage/VoyageDeleteDraftCheck.jsx
NMSW-623
----
Remove console.logs() from the code
----
- There is still a console log on the ChangeYourDetails page but this page is not being used for MVP and the console log will be removed when we add the patch to the page
=> NMSW-623 Remove console logs from code

src/components/DownloadTemplates.jsx, src/pages/Landing/Landing.jsx, src/pages/NavPages/Templates.jsx, src/pages/Regulatory/Help.jsx
NMSW-624
----
----
- Go to Landing page, Templates tab and Help tab
- The pages should look and work as expected
----
=> NMSW-624 Split template download into it's own component

src/components/FileUploadForm.jsx, src/components/MultiFileUploadForm.jsx, src/pages/NavPages/YourDetails/YourDetails.jsx, src/pages/NavPages/YourVoyages/YourVoyages.jsx, src/pages/Voyage/VoyageCheckYourAnswers/VoyageCheckYourAnswers.jsx, src/pages/Voyage/VoyageDeleteDraftCheck.jsx, src/pages/Voyage/VoyagePassengers.jsx
=> NMSW-589 Move all API auth error handling to the new function

src/components/MultiFileUpload/DragDropZone.jsx, src/components/MultiFileUpload/FileList.jsx, src/components/MultiFileUpload/FileStatus.jsx, src/components/MultiFileUpload/MultiFileUploadForm.jsx, src/components/MultiFileUpload/__tests__/MultiFileUploadErrors.test.jsx, src/components/MultiFileUpload/__tests__/MultiFileUploadForm.test.jsx, src/components/MultiFileUpload/__tests__/MultiFileUploadStatus.test.jsx, src/components/MultiFileUploadForm.jsx, src/constants/AppConstants.js, src/pages/Voyage/VoyageSupportingDocsUpload.jsx
----
- move drag/drop zone element and related to functions to own file
- move the status jsx to own file
- move the file list display component to own file and use for both file list use cases
----
----
=> NMSW-588 Refactor some of multi file upload file

public/index.html, src/constants/AppConstants.js, src/pages/Regulatory/__tests__/AccessibilityStatement.test.jsx, src/pages/Regulatory/__tests__/ContactUs.test.jsx, src/pages/Regulatory/__tests__/Help.test.jsx
----
Add contact email & text to the nojs version of the page
----
Turn off javascript
open the app
you should see the nojs page with a comment to contact us if you cannot enable javascript
----
=> NMSW-715 Update email to match main & add it to nojs code

src/components/DisplayForm.jsx, src/components/__tests__/DisplayFormTests/DisplayActionButtons.test.jsx, src/components/__tests__/DisplayFormTests/DisplayDetailsComponent.test.jsx, src/components/__tests__/DisplayFormTests/DisplayLayout.test.jsx, src/pages/NavPages/YourDetails/__tests__/ChangeYourDetails.test.jsx, src/pages/NavPages/YourDetails/__tests__/ChangeYourPassword.test.jsx, src/pages/Register/__tests__/RegisterEmailAddress.test.jsx, src/pages/Register/__tests__/RegisterYourDetails.test.jsx, src/pages/Register/__tests__/RegisterYourPassword.test.jsx, src/pages/SignIn/__tests__/RequestPasswordReset.test.jsx, src/pages/SignIn/__tests__/ResetPassword.test.jsx, src/pages/SignIn/__tests__/SignIn.test.jsx, src/pages/Voyage/__tests__/VoyageDeleteDraftCheck.test.jsx, src/pages/Voyage/__tests__/VoyagePassengers.test.jsx
----
Our forms are not submitting on enter being pressed
Need to fix the button type to submit so they will submit
----
- go to any form
- enter fields
- while a field is active press enter
- > form should attempt to submit
- > if any errors exist you should be shown errors
- > if no errors form should submit and you should move to next step
----
=> NMSW-761 Fix ability to submit form with enter click

cypress/e2e/features/check-your-answers-page.feature, cypress/e2e/features/password-reset.feature, cypress/e2e/features/your-voyage-page.feature, cypress/e2e/pages/your-voyage.page.js, cypress/support/step_definitions/declaration.steps.js, cypress/support/step_definitions/fal1-upload-general-declaration.steps.js, cypress/support/step_definitions/your-voyage-page.steps.js
Added test for NMSW-611 Paginate voyage list
For pagination feature
```
```
select your-voyage-page.feature
E2E
```
```
=> Test pagination

src/components/DisplayForm.jsx, src/components/Forms/ErrorSummary.jsx, src/components/Forms/FormActions.jsx, src/components/Forms/FormFields.jsx
----
Make file easier to manage - part 1 move the rendering into separate components
- move error summary into own component
- move form actions into own component
- move field displayer into own component
----
----
=> NMSW-621 Form refactoring

docs/form_creator_example.md, src/components/Forms/DisplayForm.jsx, src/components/__tests__/DisplayFormTests/DefaultValuesAndSessionData.test.jsx, src/components/__tests__/DisplayFormTests/DisplayActionButtons.test.jsx, src/components/__tests__/DisplayFormTests/DisplayDetailsComponent.test.jsx, src/components/__tests__/DisplayFormTests/DisplayFormInputs.test.jsx, src/components/__tests__/DisplayFormTests/DisplayLayout.test.jsx, src/components/__tests__/DisplayFormTests/ErrorClearingErrors.test.jsx, src/components/__tests__/DisplayFormTests/ErrorSpecialRules.test.jsx, src/components/__tests__/DisplayFormTests/ErrorSummaryAndLinks.test.jsx, src/pages/NavPages/YourDetails/ChangeYourDetails.jsx, src/pages/NavPages/YourDetails/ChangeYourPassword.jsx, src/pages/Register/RegisterEmailAddress.jsx, src/pages/Register/RegisterEmailResend.jsx, src/pages/Register/RegisterYourDetails.jsx, src/pages/Register/RegisterYourPassword.jsx, src/pages/Regulatory/CookiePolicy.jsx, src/pages/SignIn/RequestPasswordReset.jsx, src/pages/SignIn/ResendRequestPasswordReset.jsx, src/pages/SignIn/ResetPassword.jsx, src/pages/SignIn/SignIn.jsx, src/pages/Voyage/VoyageCheckYourAnswers/VoyageCancelConfirmation.jsx, src/pages/Voyage/VoyageDeleteDraftCheck.jsx, src/pages/Voyage/VoyagePassengers.jsx
----
Refactor display form to make easier to manage - part 2, move into a folder
- Move display form file into Form folder with other related components
This PR is mostly import path updates
----
----
=> NMSW-621 Display form location

src/App.test.jsx, src/AppRouter.jsx, src/pages/Landing/Landing.jsx, src/pages/Landing/Landing.test.jsx
----
Remove access to 'create account' page for beta period
----
- run app
- > on landing page there should be no link to create account
- try to go to /create-account/email-address
- > you should be redirected to the landing page
----
=> NMSW-782 Remove access to create account page for beta period

helm/Chart.yaml, package-lock.json, package.json, src/App.test.jsx, src/AppRouter.jsx, src/pages/Landing/Landing.jsx, src/pages/Landing/Landing.test.jsx
Merge 0.14.3 to main
This is a change for the production service
Ensure we do not promote other changes from `version-1.0.0` branch
=> Version 0.14.3

helm/Chart.yaml, package-lock.json, package.json
=> Bump version to 0.14.4

cypress/e2e/features/check-your-answers-page.feature, cypress/e2e/features/landing-page.feature, cypress/e2e/features/registration.feature, cypress/e2e/features/sign-in.feature, helm/Chart.yaml, package-lock.json, package.json
Merge version 0.14.4 into main
=> Version 0.14.4

helm/Chart.yaml, package-lock.json, package.json
=> Bump version to 0.14.5

cypress/e2e/features/fal1-error-validation.feature, cypress/e2e/features/fal5-error-validation.feature
Change of file name with case sensitive 
Run E2E
```
```
=> change test file name with case-sensitive

cypress/e2e/features/fal1-error-validation.feature, cypress/e2e/features/fal5-error-validation.feature, helm/Chart.yaml, package-lock.json, package.json
=> Version 0.14.5

cypress/e2e/features/declaration.feature, cypress/e2e/features/fa15-upload-crew-details.feature, cypress/e2e/features/fal1-error-validation.feature, cypress/e2e/features/fal6-upload-passenger-details.feature, cypress/e2e/features/landing-page.feature, cypress/e2e/features/registration.feature, cypress/e2e/features/sign-in.feature, cypress/e2e/features/task-details-page.feature, cypress/e2e/features/upload-supporting-documents.feature, cypress/e2e/pages/declaration.page.js, cypress/e2e/pages/sign-in.page.js, cypress/support/step_definitions/fal1-upload-general-declaration.steps.js
Test change with create account temporary deletion
Add delete drafts and add waits to get tests works for more declaration added
```
```
=> Test nmsw reg change

cypress/e2e/features/declaration.feature, cypress/e2e/features/fa15-upload-crew-details.feature, cypress/e2e/features/fal1-error-validation.feature, cypress/e2e/features/fal6-upload-passenger-details.feature, cypress/e2e/features/landing-page.feature, cypress/e2e/features/registration.feature, cypress/e2e/features/sign-in.feature, cypress/e2e/features/task-details-page.feature, cypress/e2e/features/upload-supporting-documents.feature, cypress/e2e/pages/declaration.page.js, cypress/e2e/pages/sign-in.page.js, cypress/support/step_definitions/fal1-upload-general-declaration.steps.js, helm/Chart.yaml, package-lock.json, package.json
=> Version 0.14.7

src/constants/AppAPIConstants.js
----
/user/declaration was removed and replaced with /declaration
----
----
=> Update declaration endpoint

cypress/e2e/pages/cya.page.js, cypress/e2e/pages/declaration.page.js, src/pages/Voyage/VoyageCheckYourAnswers/CYACallToActions.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYARender.test.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYARenderByStatus.test.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYASubmit.test.jsx
----
Update heading, paragraph, and button text on the submission section of CYA page
----
- sign in
- go to a CYA page
- content should match Jira ticket
----
=> NMSW-998 Content changes on CYA page

cypress/e2e/features/declaration.feature, cypress/e2e/pages/declaration.page.js, cypress/support/step_definitions/declaration.steps.js, src/pages/Voyage/VoyageCheckYourAnswers/VoyageCheckYourAnswers.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYASubmit.test.jsx
----
Update heading and paragraphs
----
- submit a report
- content should match the screenshot in Jira ticket
----
=> NMSW-998 Content changes on report submitted confirmation page

src/components/StatusTag.jsx, src/pages/NavPages/YourVoyages/__tests__/YourVoyages.test.jsx, src/pages/Voyage/VoyageCheckYourAnswers/CYACallToActions.jsx, src/pages/Voyage/VoyageCheckYourAnswers/CYAUploadedDocs.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYARender.test.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYARenderByStatus.test.jsx
----
If a report is PreSubmitted show a pending status tag
----
- view voyage list
- > preSubmitted reports should have yellow pending tag
- click on voyage to review
- > voyage details should have yellow pending tag
----
=> NMSW-998 Show pending status for PreSubmitted reports

helm/production.yaml, public/index.html, src/constants/AppConstants.js, src/pages/Regulatory/__tests__/AccessibilityStatement.test.jsx, src/pages/Regulatory/__tests__/ContactUs.test.jsx, src/pages/Regulatory/__tests__/Help.test.jsx
Change the email address on the help (/help-page) and Contact us (/contact-us) pages
----
- Check that all places in the code have been updated with the new email
- Run app
- Go to contact page in the footer
- > You should see the updated email
- Do the same for the help page
----
----
=> NMSW-968 Update contact email

src/components/MultiFileUpload/__tests__/MultiFileUploadErrors.test.jsx, src/components/MultiFileUpload/__tests__/MultiFileUploadForm.test.jsx, src/components/MultiFileUpload/__tests__/MultiFileUploadStatus.test.jsx, src/pages/Voyage/VoyageCheckYourAnswers/VoyageCheckYourAnswers.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYARender.test.jsx, src/pages/Voyage/VoyageCheckYourAnswers/__tests__/VoyageCYARenderByStatus.test.jsx, src/pages/Voyage/VoyageTaskList.jsx, src/pages/Voyage/__tests__/VoyageSupportingDocsUpload.test.jsx, src/pages/Voyage/__tests__/VoyageTaskList.test.jsx, src/pages/Voyage/__tests__/fixtures/getVoyage-Cancelled.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Failed.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5Fal6.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5Fal6Supporting.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5PassengersFalse.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5PassengersFalseSupporting.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5PassengersTrue.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5PassengersTrueSupporting.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal5Supporting.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal6.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Fal6Supporting.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1PassengersFalse.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1PassengersTrue.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1Supporting.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1SupportingPassengersFalse.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Fal1SupportingPassengersTrue.js, src/pages/Voyage/__tests__/fixtures/getVoyage-PreCancelled.js, src/pages/Voyage/__tests__/fixtures/getVoyage-PreSubmitted.js, src/pages/Voyage/__tests__/fixtures/getVoyage-Submitted.js
NMSW-1013
----
Update references to FAL1 to be declaration due to change in response from API
----
- Check that all FAL1 references in code are updated to 'declaration' and FAL1 is now added as an array in tests like FAL5 and 6 to match BE response
----
=> NMSW-1013 Update 'FAL1' references to 'declaration' to match API change

cypress/e2e/components/cookie.comp.js, cypress/e2e/features/your-voyage-pagination.feature, cypress/e2e/pages/cookie.page.js, cypress/support/commands.js, cypress/support/step_definitions/check-your-answers-page.steps.js, cypress/support/step_definitions/cookieSteps.js, cypress/support/step_definitions/declaration.steps.js, cypress/support/step_definitions/fal1-upload-general-declaration.steps.js, cypress/support/step_definitions/fal5-upload-crew-details.steps.js, cypress/support/step_definitions/fal6-upload-passenger-details.steps.js, cypress/support/step_definitions/landing-page.steps.js, cypress/support/step_definitions/password-reset.steps.js, cypress/support/step_definitions/registration.steps.js, cypress/support/step_definitions/sign-in.steps.js, cypress/support/step_definitions/task-page.steps.js, cypress/support/step_definitions/templates.steps.js, cypress/support/step_definitions/upload-supporting-documents.steps.js
Added timeout to avoid test failure with loading time
```
```
=> Fix failing test

src/pages/Voyage/VoyageTaskList.jsx
NMSW-1036
----
Fix accessibility issue where FAL 5 & 6 had identical ids
----
=> NMSW-1036 Fix duplicate id

helm/Chart.yaml, package-lock.json, package.json
=> Bump to version-1.0.2

cypress/e2e/features/registration.feature, cypress/support/step_definitions/password-reset.steps.js, cypress/support/step_definitions/sign-in.steps.js
Change the test email used for unverified email scenario
```
npm run cypress:open:dev
```
Select sign-in.feature and password-reset.feature
----
=> Change email for Unverified email test

cypress/e2e/features/registration.feature, cypress/support/step_definitions/password-reset.steps.js, cypress/support/step_definitions/sign-in.steps.js, helm/Chart.yaml, package-lock.json, package.json, src/pages/Landing/Landing.jsx, src/pages/Landing/Landing.test.jsx, src/pages/SignIn/SignIn.jsx, src/pages/SignIn/__tests__/SignIn.test.jsx
=> Version 1.0.2

helm/Chart.yaml, package-lock.json, package.json
=> Bump to version-1.0.3

cypress/e2e/features/sign-in.feature, cypress/e2e/pages/sign-in.page.js, cypress/fixtures/registration.json, cypress/support/step_definitions/password-reset.steps.js, cypress/support/step_definitions/registration.steps.js, cypress/support/step_definitions/sign-in.steps.js, cypress/support/step_definitions/templates.steps.js, cypress/support/step_definitions/your-voyage-pagination.steps.js, helm/Chart.yaml, package-lock.json, package.json
=> Version-1.0.3

helm/Chart.yaml, package-lock.json, package.json
=> Bump to version 1.0.4

.drone.yml, cypress.config.js, helm/Chart.yaml, package-lock.json, package.json
=> Version 1.0.4

README.md, docs/packages.md
----
Add links to EULA's for all packages used
----
- View readme file
- go to the packages section
- check each package we have in package.json is listed in the Readme
----
=> NMSW-1121 Add list of packages and link to EULA to README

.github/dependabot.yml
NMSW-1186
----
Enable dependabot version updates
----
=> NMSW-1186 Add dependabot version updates

cypress/config/drone-dev.config.js, cypress/config/drone-staging.config.js, drone-cypress-test-script.sh, package.json
----
Add Cypress config for drone so it can run
----
----
=> NMSW-1237 Update cypress config for drone

src/components/Pagination/__tests__/PaginationClick.test.jsx, src/components/Pagination/__tests__/PaginationSetup.test.jsx
Commenting out pagination tests while we resolve the issue of them failing due to other tests not clearing ahead of them
=> Comment out pagination tests until we can resolve clearing issue

docs/form_creator.md, helm/Chart.yaml, package-lock.json, package.json, src/components/Forms/DisplayForm.jsx, src/components/Pagination/__tests__/PaginationClick.test.jsx, src/components/Pagination/__tests__/PaginationSetup.test.jsx, src/components/__tests__/DisplayFormTests/DefaultValuesAndSessionData.test.jsx, src/constants/AppConstants.js, src/pages/Register/RegisterEmailAddress.jsx, src/pages/Register/__tests__/RegisterRestrictedEmails.test.jsx, src/pages/SignIn/SignIn.jsx
Merge commits from https://github.com/UKHomeOffice/nmsw-ui/pull/576
& release next version
=> Version 1.0.7

package-lock.json, package.json
Update packages inline with 1.1
=> Change xl converters

src/AppRouter.jsx, src/assets/css/yourVoyages.scss, src/constants/AppUrlConstants.js, src/pages/NavPages/YourVoyages/YourVoyages.jsx, src/pages/NavPages/YourVoyages/__tests__/YourVoyages.test.jsx, src/pages/Regulatory/ETA/EtaRequirements.jsx, src/pages/SignIn/SignIn.jsx, src/pages/SignIn/__tests__/SignIn.test.jsx, src/utils/cookieToFind.js
----
- on sign in take user to ETA page
- set cookie to say they've seen it
- on next sign in, if cookie exists do not show ETA page
----
- sign in
- > you should see ETA page
- sign out
- sign in
- > you should not see ETa page
- delete cookie for eta
- sign in
- > you should see ETA page
----
=> NMSW-1372 Add interstitial page on sign in to go to ETA page

src/AppRouter.jsx, src/assets/css/eta.scss, src/assets/css/yourVoyages.scss, src/components/MultiFileUpload/DragDropZone.jsx, src/components/StatusTag.jsx, src/constants/AppConstants.js, src/constants/AppUrlConstants.js, src/pages/NavPages/YourVoyages/YourVoyages.jsx, src/pages/NavPages/YourVoyages/__tests__/YourVoyages.test.jsx, src/pages/Regulatory/ETA/EtaRequirements.jsx, src/pages/Regulatory/ETA/__tests__/EtaRequirements.test.jsx, src/pages/Regulatory/Help.jsx, src/pages/Regulatory/__tests__/Help.test.jsx, src/pages/SignIn/SignIn.jsx, src/pages/SignIn/__tests__/SignIn.test.jsx, src/utils/cookieToFind.js
----
Add UPT email to help page
Add ETA requirements page
----
- log into app
- go to 'help' menu
- > you should see the UPT email address on the second line of the details section
- > this should match the design in the ticket
ETA page content - unit tests should pass
----
ETA help page is started here but properly testable in next PR
=> NMSW-1372 Add ETA page and UPT email
