UKHomeOffice/nmsw-ui

- src/App.jsx
- src/assets/main.scss
- src/layout/Footer.jsx
- src/layout/__tests__/Footer.test.jsx
NMSW-10
----
GIVEN The product site is up
WHEN I go to /
THEN I am shown the landing page for the product 
AND I can see the GDS styled footer
----
- > you should see the GDS footer with the Crown copyright logo
_the Crown copyright logo will not link to anywhere_
----
The logo element will fail axe checks for colour contrast. It's a known situation https://github.com/alphagov/govuk-frontend/issues/2134
- add GDS footer
- comment out code for footer links as we don't need them now but will need them soon
- add background colour to body that matches footer background colour so if a page is shorter than the window it fills with the footer colour and not the content colour
- add background colour to root element (main div ID within body) that matches …
> NMSW-10 Add GDS Footer

- src/App.jsx
- src/layout/CookieBanner.jsx
- src/layout/__tests__/CookieBanner.test.jsx
NMSW-22
----
GIVEN I am visiting the site
WHEN I have no stored cookie consent information
THEN I am shown the GDS cookie banner 
----
- > you should see a banner at the top of the page with a h2 of 'Cookies on National Maritime Single Window'
- >and a paragraph of'We use some essential cookies to make this service work.'
- and a second paragraph of
- >'We'd like to set additional cookies so we can remember your settings, understand how people use the service and make improvements.'
- there will be no buttons or links on this version
- there is no way to turn off the banner yet
----
> NMSW-22 Create cookie banner

- src/App.jsx
- src/App.test.jsx
- src/constants/AppConstants.js
- src/layout/PhaseBanner.jsx
- src/layout/__tests__/PhaseBanner.test.jsx
NMSW-9
----
GIVEN The product site is up
WHEN I go to /
THEN I can see the GDS Beta phase banner
----
- > you should see the beta phase banner
----
We don't have a link for the feedback banner yet - see ticket NMSW-46
- added GDS Phase Banner component
- added a role so that it was contained within a landmark for accessibility
- updated App.jsx test to test for header, footer, phase banner
- added unit tests for PhaseBanner
> NMSW-9 Add GDS Phase Banner component

- src/App.jsx
- src/App.test.jsx
- src/layout/Header.jsx
- src/pages/LandingPage/Landing.jsx
- src/pages/LandingPage/LandingPage.test.jsx
NMSW-11
----
GIVEN The product site is up
WHEN I go to /
THEN I am shown the landing page for the product 
AND I can see a page with a h1
----
- you should see a page header with the GOVUK logo & a product title of National Maritime Single Window
- neither of these will have links
- you should see the GDS beta phase banner
- you should see the GDS footer with the crown copyright logo
- there will be no links in the footer
- you should see a H1 saying National Maritime Single Window
- you should see paragraph text saying Use this service to:
----
- NMSW-47 created for when we have content for this page
- added a data-testid to the service name in the header so we can target that in tests to ensure it's rendering correctly when the service name is …
> NMSW-11 Add Landing page

- .eslintrc.json
- src/index.js
NMSW-13
----
Noticed an odd `,` on the page in the root element that shouldn't be there - removed it
Also identified it was resulting in aXe tools reporting that content on the page wasn't contained in a landmark
----
- scroll to the footer
- > there should be no white background below the footer
- > there should be no comma below the footer
- run aXe devtools
- > there should be no landmark issues
----
> NMSW-13 Remove rogue comma

- src/AppRouter.jsx
- src/utils/ScrollToTop.js
NMSW-62
----
GIVEN I have clicked on an internal link
WHEN the new page component loads
THEN I should be able to see the top of the page
----
- go to any page
- shrink your browser so you have to scroll to get to the footer and cannot see the H1 when you do
- scroll to the footer
- click the 'cookies' link
- > the cookie page should load and scroll to the top of the page where you can see the H1
----
> NMSW-62 Add auto scroll to top on page change

- src/AppRouter.jsx
- src/layout/CookieBanner.jsx
- src/layout/__tests__/CookieBanner.test.jsx
- src/pages/Regulatory/__tests__/CookiePolicy.test.jsx
NMSW-26
----
Given I am viewing the cookie banner
When I click on the view cookies link
Then I am shown the cookie page
Given I have selected accept or reject on the cookie banner
And am viewing the confirmation page
When I click on the 'change your cookie settings' link
Then I am shown the cookie page
----
- To Test
- If present, delete cookiePreference cookie
- > you should see the cookie banner at the top of the page
- it should have a view cookies link
- click the view cookies link
- > you should be taken to the cookie page
- there will be no content on this page at this time
- go back to the cookie banner
- select accept or reject
- > you should see the confirmation of cookie selected panel
- click on 'change your cookie settings'
- > you …
> NMSW-26 Add link to CookieBanner

- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/InputRadio.jsx
- src/components/formFields/__tests__/InputRadio.test.jsx
- src/pages/Regulatory/CookiePolicy.jsx
Prep for NMSW-120
----
n/a
----
Run RTL tests
----
Extending tests within form creator so we can use them as additional documentation on how to build forms with the creator
- removed some unneeded propTypes 
- made radioOptions required propTypes as we can't create radios without it
- added a formId for Cookie form as formId is now required (wasn't previously)
- added unit tests for InputRadio
- added integration tests for DisplayForm
> NMSW-120 Extend test coverage

- src/AppRouter.jsx
- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/InputRadio.jsx
- src/components/formFields/__tests__/InputRadio.test.jsx
- src/constants/AppConstants.js
- src/constants/AppUrlConstants.js
- src/layout/Nav.jsx
- src/pages/Confirmation/FormConfirmationPage.jsx
- src/pages/Confirmation/FormConfirmationPage.test.jsx
- src/pages/Regulatory/CookiePolicy.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-31
----
Given I am on the second page form
When I submit a valid form (all mandatory fields have a value)
Then I am taken to a confirmation page
And I can see a link to return to the dashboard
Given I am on the confirmation page
When I click the link to return to the dashboard
Then I am taken back to the dashboard
----
- click start now
- click sign in
- click second page in nav
- fill out the form on the second page
- click submit
- > you should see a confirmation of successful submission
- > you should see a reference number
- > you should see a what happens next section
- > you should see a button to continue to the next suggested page (for this form it will be dashboard)
- click the link
- > you should be returned to the dashboard
- go to …
> NMSW-31 Form creator adapt InputRadio to take 3+ items, add form confirmation of submission page

- .drone.yml
- README.md
- helm/Chart.yaml
- package-lock.json
- package.json
NMSW-138
----
Upgrade to Node 18
----
- Delete your `/node-modules` folder and everything within
- Delete your `package-lock.json` file
- Run `npm i`
- Run `npm start` 
- > app should run on localhost:3000
- Run `npm run test`
- > tests should pass
- Stop the app
- Run `docker build -t nmsw-ui .` to build the app Docker container
- Run `docker run --name nmswui -p 8080:8080 nmsw-ui .` to run the Docker container
- > app should run on localhost:8080
----
> NMSW-138 - Upgrade to node 18, bump app version

- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/InputRadio.jsx
- src/components/formFields/InputText.jsx
- src/components/formFields/__tests__/InputRadio.test.jsx
- src/components/formFields/__tests__/InputText.test.jsx
- src/pages/Regulatory/CookiePolicy.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
NMSW-94
----
Given I am on a form
When I have entered anything into the form fields
And I refresh the page
Then the answers I have entered persist (they are not cleared)
Given I have refreshed the page and answers have persisted
When I submit the form
Then the fields that were persisted should be accepted and not error
Given I am on a form with a password field
When I have entered something in that field
And I refresh the page
Then the password field should become blank (we do not persist passwords)
----
- click sign in
- enter something in every field
- click refresh
- > email should remain
- > password should be cleared (not persisted)
- > sample field should remain
- click sign in button
- > password field should error
- enter password
- click sign in button
- > you …
> NMSW-94 Persist most form data on page refresh (not passwords, not cookie preference)

- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/pages/Regulatory/CookiePolicy.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-160
----
Given I have entered valid answers in a form
When I click submit
And I then return back to the form
Then the form is clear (answers do not persist after submit)
----
- sign in
- >  second page form form should be empty
- enter something in second page form form fields
- refresh page
- > values you entered should remain
- click submit
- > you should be taken to the confirmation page
- click to go to dashboard
- go back to  second page form
- > form should be empty
----
Decided in the interest of not replicating code unnecessarily, and in the interest of reducing room for error, to move the validation call and error handling within the DisplayForm component
> NMSW-160 Move validation to inside DisplayForm component and clear sessionStorage when form ready for submit

- cypress/e2e/pages/cookie.page.js
n/a
----
Update Cypress tests to use the new values for the yes/no radio buttons on the cookie page
----
Run Cypress tests, they should pass
----
We changed the values from true/false to yes/no in a previous PR as they were causing problems elsewhere using strings for true and false
> Update cypress tests for cookie page radio

- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
NMSW-33
----
Separating https://github.com/UKHomeOffice/nmsw-ui/pull/58 into multiple PRs for ease of review
This ticket removes the sample field we had to allow testing of some validation. We do not need this field on the sign in page.
----
- view sign in page
- there should only be email and password fields
----
There is still no authentication
> NMSW-33 Remove sample fields from sign in page

- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/DetermineFieldType.jsx
- src/components/formFields/InputConditional.jsx
- src/components/formFields/__tests__/InputConditonal.test.jsx
- src/constants/AppConstants.js
- src/pages/TempPages/SecondPage.jsx
- src/utils/Validator.jsx
NMSW-140
----
Given I am on a form with conditional fields
When I select an option that has a connected text input
Then I should see the connected text input
Given I am on a form with conditional fields
When I select an option that does not have the connected text input
Then I should not see the connected text input
----
- run locally
- > the last question should be a set of radio buttons
- select `dog`
- > the breed of dog question should be shown
- type something in that field
- select `cat`
- > the breed of dog field should be hidden
- > the breed of cat field should be displayed
- select `dog`
- > the breed of dog field should be shown
- > the breed of cat field should be hidden
- select `rabbit`
- > the breed of dog field should be hidden
----
- there is no …
> NMSW-140 Radio buttons with conditional text fields component (no errors or persisting values yet)

- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/InputConditional.jsx
- src/components/formFields/__tests__/InputConditonal.test.jsx
NMSW-140
----
Given I have clicked on a radio with a connected field
When I enter something in that field
And refresh the browser
Then the radio I've selected remains selected
And the value I've entered in the connected field remains
----
- go to second page
- click on `cat`
- type something in the text field
- refresh browser
- > cat should remain selected
- > the text you typed should remain in the text field
----
If you 
- select a radio with a conditional field
- enter something in the conditional text field
- hit refresh
- submit the form with. no other actions
- > the conditional field value is not submitted
This is being worked on now
> NMSW-140 Extend conditional field input to persist data on refresh

- src/components/formFields/InputConditional.jsx
- src/components/formFields/InputText.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-140
----
To replicate bug
- select a radio with a conditional field
- enter something in the conditional text field
- hit refresh
- submit the form with. no other actions 
- > the conditional field value is not submitted
----
To test
- run locally
- enter a first name
- select a colour
- select `cat`
- enter something in `breed of cat`
- refresh page
- submit the form with no other actions 
- > the confirmation page should load
- > the reference should include what you typed in breed of cat to show it is being passed through
----
> NMSW-140 Bug fix, conditional field value not storing in form data on page refresh and persist -- FIXED

- package-lock.json
- package.json
- src/assets/main.scss
NMSW-33
----
Install package in preparation for use
https://github.com/alphagov/accessible-autocomplete
----
- remove node-modules
- run `npm ci`
- `"accessible-autocomplete": "^2.0.4"` should be listed in dependencies
----
> NMSW-33 Install alphagov accessible autocomplete and style needs

- src/assets/main.scss
- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/DetermineFieldType.jsx
- src/components/formFields/InputAutocomplete.jsx
- src/components/formFields/__tests__/InputAutocomplete.test.jsx
- src/constants/AppConstants.js
- src/pages/Regulatory/__tests__/CookiePolicy.test.jsx
- src/pages/TempPages/SecondPage.jsx
- src/pages/TempPages/TempMockList-countries.js
- src/pages/TempPages/TempMockList-portList.js
NMSW-33
----
Given I have to select from a predefined list of items
When I start to type an items name (After 2 characters)
Then I am shown a list of options that could match that item (From start of word)
----
- go to country question
- type 2 letters of a country
- > you should see countries that match those letters in the list
- select a country
- go to the port question
- type `do` (we only have dover and portsmouth ports in the list right now)
- > you should see options for `Dover GB DOV` and `Dover Marina` and `Dover Other GB POR`
- select a port
- fill out rest of form
- click submit
- form should submit
- confirmation page reference should include the country and port you selected
----
- there is no persist data on refresh yet
- there is …
> NMSW-33 Add basic autocomplete component

- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/components/formFields/InputAutocomplete.jsx
- src/constants/AppConstants.js
- src/pages/TempPages/SecondPage.jsx
NMSW-33
----
Given an autocomplete field's selected value has additional details
When the form is submitted
Then the additional details should be sent with the form data
----
- run locally
- go to second form
- fill in all fields
- for port select a port with a unlocode (eg Dover GB DOV)
- click submit
- > the submitted data should include extended data for country (name, code) and port (name, unlocode)
- > the confirmation page should show the country code and unlocode
- go back to second form
- fill in all fields
- for port select a port with NO unlocode (eg Dover Marina)
- click submit
- > the submitted data should include extended data for country (name, code) and port (name)
- > the confirmation page should show the country code correctly, and the unlocode as UNDEFINED
----
Field has …
> NMSW-33 Expand autocomplete component to submit additional data

- src/components/formFields/InputAutocomplete.jsx
- src/components/formFields/__tests__/InputAutocomplete.test.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-33
----
Given I have selected a value in an autocomplete field
When I refresh the page
Then the data should persist in the field
~~Given I have selected a value in an autocomplete field
And I have refreshed the page
When I submit the form
Then the full data should be submitted~~
Given I have attempted to submit a form with an autocomplete field
When the field is required
And has no value
Then an error should be shown
----
- run locally
- go to second page
- submit the form
- > the country field should error
- > the port field should error
- select a country
- refresh the page
- > the country field should remain populated
- select a port field with a unlocode
- refresh the page
- > the port field should persist with `name unlocode`
- submit the form
- > the form should submit
---- …
> NMSW-33 Extend autocomplete component to persist data on refresh and handle errors

- src/components/formFields/InputAutocomplete.jsx
- src/components/formFields/__tests__/InputAutocomplete.test.jsx
NMSW-205
----
Unable to replicate the value not persisting on local env - so needs to be tested on built version
Given I have typed at least two characters in an autocomplete field
When the list is displayed
Then I should see options related to what I typed
Given I can see a list of options
When I select an item from the list
Then it should show in the input field
Given I have a value in the input field
When I refresh the page
Then the value should persist
Given I have seen a value persist once
When I refresh the page again
Then the value should STILL persist
----
- make sure you're running docker
- `docker build -t nmsw-ui .`
- `docker run --name nmswui -p 8080:8080 nmsw-ui .`
- in browser go to localhost:8080
- type into the autocomplete fields
- select an item
- > check session data to …
> NMSW-205 Autocomplete not persisting values correctly

- docs/form_creator.md
- docs/form_creator_example.md
- public/index.html
- src/AppRouter.jsx
- src/components/DisplayForm.jsx
- src/constants/AppConstants.js
- src/constants/AppUrlConstants.js
- src/pages/Landing/Landing.jsx
- src/pages/Landing/Landing.test.jsx
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterEmailAddress.test.jsx
- src/utils/Validator.jsx
NMSW-155
----
GIVEN I have followed a link to the website
WHEN I arrive on the landing page
THEN there is an option to "Create an account"
GIVEN I have selected to create an account
WHEN the registration page is displayed
THEN I am able to provide the following details:
*Email address
*Confirm email address
Given I provided my email address CORRECTLY
AND they match
When I submit them
Then I am redirected to provide my other details:
----
- run locally
- click on `create account`
- > you should be taken to a page with h1 `What is your email address`
- > page should have a form with fields for email and confirm email
- click continue
- > both fields should error
- enter something in email address field that is not an email
- click continue
- > field should error as invalid
- enter an email …
> NMSW-155 New routes & field match validator

- docs/form_creator.md
- docs/form_creator_example.md
- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/pages/Regulatory/CookiePolicy.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-117
----
Given I have cancelled a form that has values added
When I then return back to the form
Then the form is clear (i.e. answers do not persist after cancel)
----
- click sign in to go to second page
- > second page form should be empty
- enter something in form fields
- refresh page
- > values you entered should remain
- click cancel
- go back to second page form
- > form should be empty
----
> NMSW-117 Do not persist data after form cancel button click

- docs/form_creator.md
- docs/form_creator_example.md
- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/constants/AppConstants.js
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterYourDetails.test.jsx
- src/pages/Register/__tests__/RegisterYourPassword.test.jsx
- src/pages/Regulatory/CookiePolicy.jsx
- src/pages/SignIn/SignIn.jsx
NMSW-155
----
When a form is more than one page long pre submission to API data needs to
- persist in the session
- persist in the form data so it can be submitted
----
- run app
- open dev tools
- go to create account
- complete email page & continue
- complete your details page & continue
- check session data
- > you should see the your details data under formData in the session
- enter password
- > you should see the password now included with the other details data in formData in the session
- switch to viewing console in dev tools
- confirm password
- click submit
- > you should be taken to the confirmation page
- > you should receive a log in the console of the formData being submitted
- > this log should include values from your details and password page
- switch to viewing session …
> NMSW-155 Multi page forms

- src/AppRouter.jsx
- src/constants/AppUrlConstants.js
- src/hooks/usePostData.js
- src/pages/Error/GenericUnknownError.jsx
- src/pages/Error/__tests__/GenericUnknownError.test.jsx
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/__tests__/RegisterEmailAddressPost.test.jsx
NMSW-155
----
To enable testing add the base of an error handling page
And on any error redirect to this page with a message
This is needed so we can easily test what happens if the /registration endpoint returns anything other than a 200
----
- run app
- go to create account
- enter a new email address & repeat
- click continue
- > you should be taken to the your details page
- go back
- enter the same email address in the email fields
- click continue
- > you should be taken to the error page with a message that the email address already exists
----
This is not the final implementation of any error handling, this is a basic form to allow testing.
Tickets are open to handle 4xx and 500 errors
> NMSW-230 Add basic error page

- src/AppRouter.jsx
- src/constants/AppUrlConstants.js
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/__tests__/RegisterYourDetails.test.jsx
NMSW-155
----
Given I have gone to `/create-account/your-details`
When there is no `email address` available in state
Then I should be redirected to the validate email page
----
- start a new browser session (new tab or new browser instance - this is to ensure there's nothing in your state)
- go to `http://localhost:3000/create-account/your-details`
- > you should be immediately redirected to `http://localhost:3000/create-account/email-verified`
- enter an email address (any, this is for testing only there is no validation here)
- click continue
- > you should be taken to your details
----
We will change which page you're redirected to in future when the verify email process is built. For now this page allows testers to enter an email address and continue testing the registration flow
> NMSW-233 Redirect if no email address when loading register your details page

- src/hooks/usePatchData.js
- src/pages/Register/RegisterEmailVerified.jsx
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterEmailAddress.test.jsx
- src/pages/Register/__tests__/RegisterYourPassword.test.jsx
NMSW-155
----
Given I have clicked submit on the create-account/your-password page
When I have no errors
Then the code sends a PATCH request to /registration
Given a PATCH request has been sent to /registration
When a success (200) response is received
Then I am taken to the confirmation page
Given a PATCH request has been sent to /registration
When an error response is received
Then I am redirected to the error page
Given a PATCH request has been sent to /registration
When no valid response is received
Then I am redirected to the error page
(this scenario is not tested in the UI, it's the `catch` scenario of the try/catch for if a promise fails unexpectedly)
----
- run BE in docker
- run app
- go to `http://localhost:3000/create-account/email-verified`
- enter an email address you have …
> NMSW-234 PATCH registration

- docs/form_creator.md
- src/constants/AppConstants.js
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterYourPassword.test.jsx
- src/utils/Validator.jsx
NMSW -226
----
Given I click submit
When there are spaces in the password value
Then I am shown an error
----
- run app
- go to /create-account/your-password
- click submit
- > `Enter a password` error should be displayed
- enter a password that has spaces in it but is less than 10 characters
- click submit
- > `Password must be at least 10 characters` error should be displayed
- enter a password that is 10 spaces only
- click submit
- `Enter a password` error should be displayed
- enter a password that is at least 10 character and has no spaces
- enter confirmation password as the same
- click submit
- > no errors should show
- > if you have the BE running in docker you should be taken to the confirmation page
----
> NMSW-226 Do not allow spaces in password creation fields

- src/App.jsx
- src/App.test.jsx
- src/constants/AppUrlConstants.js
- src/layout/Nav.jsx
- src/layout/__tests__/Nav.test.jsx
- src/pages/Landing/Landing.jsx
NMSW-119
----
Given I have entered anything into form fields
When I go to a different section of the site
And I then return back to the form
Then the form is clear (answers do not persist across site sections)
----
- click sign in to go to second page
- > second page form should be empty
- enter something in second page form fields
- refresh page
- > values you entered should remain
- click on dashboard page in nav
- go back to second page 
- > form should be empty
- enter something second page form fields
- type the /dashboard url into the address bar
- go back to second page 
- > form should be empty
- enter something in second page form fields
- click on a link from the footer
- go back to second page 
- > form should be empty
- enter something in second page form …
> NMSW-119  Do not persist form data when user moves to another section of the site

- src/assets/main.scss
- src/components/DisplayForm.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
NMSW-219
----
Given I click on the create one now link
Then I am taken to the /create-account/email-address page 
----
- go to sign in page
- there should be a create one now link
- click the link
- you should be taken to /create-account/email-address
----
> NMSW-219 Add create account link to sign in page

- src/AppRouter.jsx
- src/constants/AppUrlConstants.js
- src/pages/Error/AccountAlreadyActive.jsx
- src/pages/Error/GenericUnknownError.jsx
- src/pages/Error/__tests__/AccountAlreadyActive.test.jsx
- src/pages/Error/__tests__/GenericUnknownError.test.jsx
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/__tests__/RegisterEmailAddressPost.test.jsx
NMSW-178
----
**Scenario: Submit email address for existing account**
GIVEN I have completed my email address on the create account/email address page
AND the email address HAS already been used for an active account
AND a verification request is NOT currently active
WHEN I submit it
THEN an error page is shown with a "400: User is already registered" message
AND a link to the sign-in page
**ACTIONS:**
Given the app has requested account creation
When an error response is received
Then I am shown the Error page with the relevant error message and link
----
- run app
- go to create account
- enter an email address for an existing account
- > you should be taken to account already active page
- > your email address should be in text
- > there should be a sign in link
- click sign in
- > you …
> NMSW-178 Error/Account exists page

- public/index.html
----
Hidden fields component is showing fields when they should be hidden
>> discovered it was due to an error in having `class` instead of `className`
----
- run app
- open second page
- > conditional fields should be hidden 
- click on cat
- > conditional field should show
----
> Change class to className so js css is applied properly

- src/App.test.jsx
- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayForm.test.jsx
- src/constants/AppConstants.js
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-167
----
Enabler for redirecting a user via the sign-in page if a token expires/doesn't exist/is invalid
Given a user successfully submits in on the sign in page
When there is a redirectURL in the state
Then the URL in the redirectURL value is loaded
Given a user successfully submits in on the sign in page
When there is NO redirectURL in the state
Then the dashboard is loaded
Given a user has been redirected to sign in from a form page
And they had filled in some of the fields on that page
When they successfully sign in
And are returned to the form page
Then the values of the fields they filled in are persisted
----
- run app
- sign in
- go to second page
- fill in some files
- click the 'redirect to sign in' test button
- > you should be taken to sign in page
- sign in (note this is …
> NMSW-167 Enable redirect via sign in

- src/context/userContext.js
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
NMSW-167
----
Given the user has successfully submitted the sign in form
When the email address from the sign in attempt is NOT the same as the email address in user context
Then clear any form session data
----
- make sure you have a new version of the app running (new tab)
- run app
- sign in
- enter something in the form
- click the redirect to sign in button
- sign in with a DIFFERENT email address
- > you should be returned to second page form
- > there should be no prefilled data
- make sure you have a new version of the app running (new tab)
- run app
- sign in
- enter something in the form
- click the redirect to sign in button
- sign in with the SAME email address
- > you should be returned to second page form
- > the data should …
> NMSW-167 Handle different user sign in after expired token style scenario

- src/constants/AppAPIConstants.js
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterEmailAddressPost.test.jsx
- src/pages/Register/__tests__/RegisterYourPassword.test.jsx
NMSW-166
----
Handle 500 errors
----
Review tests
run unit/integration tests
they should pass
----
- added handling for if axios itself throws an error
- made the generic fallback error handling not require a message so it can handle 500 responses
> NMSW-166 Handle axios or 500 error responses

- src/AppRouter.jsx
- src/assets/main.scss
- src/assets/table.scss
- src/constants/AppUrlConstants.js
- src/pages/Voyage/ErrorsCrewUpload.jsx
- src/pages/Voyage/__tests__/ErrorsCrewUpload.test.jsx
NMSW-291
----
Given I am on the error page for Crew details upload
I will see a H1 with 'Errors found' and text detailing that there are errors
Given I am on the error page for Crew details upload
I see a (table) with a red sidebar containing information about (mocked) errors 
The table will show a (possible) cell number in one column and a concatenated cell value - error message in a second column
Given there is 1 error
I see one error in the (table)
Given there are 5 errors
When I map over the errors
Then I will see a (table) with 5 errors
Given there are 100 errors
When I map over the errors
Then I will see a table with 100 errors (Need a way to deal with this many errors - this is to demo what lots of errors will look like)
----
- Run the app
- Sign in
- in the url type …
> NMSW-291 Crew details upload - Error page (mocked errors)

- src/components/__tests__/DisplayFormTests/ErrorPhoneNumberInput.test.jsx
- src/components/__tests__/DisplayFormTests/ErrorSummaryAndLinks.test.jsx
----
We occasionally had 2 tests failing inexplicably and randomly - they would fail when we'd not touched related code, and if you run the test suite again then they would pass.
Investigating it looks like the `expect` statement that checked for error text to have appeared on the page was running before the errors has been generated.
To try to prevent this we've added waits around the error summary title to wait for it to appear before running the rest of the assertions
> Add a wait in tests to prevent timing errors

- .eslintrc.json
- src/constants/AppAPIConstants.js
- src/constants/AppUrlConstants.js
- src/pages/Register/RegisterEmailVerified.jsx
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterEmailVerified.test.jsx
- src/pages/Register/__tests__/RegisterYourDetails.test.jsx
NMSW-180
----
Given a user clicks their 'verify your email address' link in their email
When the FE receives that request
Then the FE sends a GET request to /check-token endpoint with the token details from the link
Given the FE app has sent a  GET request to /check-token endpoint
When the response is 204
Then the email address verified page is loaded with a continue button
Given the user has been shown the email address verified page
When they click the continue button
Then they are taken to the /your-details page 
Given they are taken to the /your-details page
When they complete the registration form and submit
Then their account is activated
----
-   // to test this as a user in browser
-   // make new email address
-   // add email to GovNotify
-   // create account using that email
- …
> NMSW-180 Verify email address - success path

- src/constants/AppAPIConstants.js
- src/pages/Register/RegisterEmailVerified.jsx
- src/pages/Register/__tests__/RegisterEmailVerified.test.jsx
NMSW-181
----
Given a user clicks their 'verify your email address' link
When the FE receives that request
Then the FE sends a GET request to /check-token endpoint with the token details from the link
Given the FE app has sent a  GET request to /check-token endpoint
When the response is 401: "Token was already used"
Then we show the user the 'error' page with 'You already have an account' message and sign in link
Given the user is on the error page
When the error reason is 'You already have an account'
And the user clicks the button
Then they're taken to the /sign-in page
----
- go to /create-account/email-address
- add new email address and submit
- you should be taken to confirm your email page
- > you should have a verification email
- click the verification email link
- > you should …
> NMSW-181 Verify email - account already exists

- docs/form_creator.md
- docs/form_creator_example.md
- src/components/__tests__/DisplayForm.test.jsx
- src/components/__tests__/DisplayFormTests/DisplayLayout.test.jsx
- src/components/__tests__/DisplayFormTests/ErrorClearingErrors.test.jsx
- src/components/__tests__/DisplayFormTests/ErrorSummaryAndLinks.test.jsx
- src/components/formFields/DetermineFieldType.jsx
- src/components/formFields/__tests__/InputConditonal.test.jsx
- src/components/formFields/__tests__/InputRadio.test.jsx
- src/constants/AppConstants.js
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Regulatory/CookiePolicy.jsx
- src/pages/TempPages/SecondPage.jsx
NMSW-168
----
The ticket requires an email input field contained within a details component. 
This PR creates that in our form creator
----
- run app & login
- open second page
- > the first form field should be a `<details>` link
- click the link
- > the email address field should be displayed
- submit the form
- > it should error as normal
- complete the form and then submit
- > it should continue to the confirmation page as normal
----
If you do not expand the details field and click submit it will still error as the validation is set to be required for this form.
To enable this, I've had to change the ternary of grouped vs single to be an option of grouped, details, or single
To prevent existing things breaking I've also set the default to always be `single` so if no display type is …
> NMSW-168 Add a details input field

- src/AppRouter.jsx
- src/components/DisplayForm.jsx
- src/components/formFields/DetermineFieldType.jsx
- src/constants/AppUrlConstants.js
- src/pages/NavPages/YourVoyages.jsx
- src/pages/Voyage/VoyageDeleteDraftCheck.jsx
- src/pages/Voyage/VoyageTaskList.jsx
- src/pages/Voyage/__tests__/VoyageDeleteDraftCheck.test.jsx
NMSW-324
----
prototype: /mvp-2/delete-draft
Page | URL | Link type | Link name | Link route | Next page
-- | -- | -- | -- | -- | --
Are you sure delete draft | /report-voyage/confirm-delete-draft | primary button | Confirm | /your-voyages | Yes: Your voyages with confirmation banner
Are you sure delete draft | /report-voyage/confirm-delete-draft | primary button | Confirm | /report-voyage | No: Draft task list
----
- run tests, all should pass
- run app
- go to `/report-voyage`
- click `delete`
- > you should be taken to `/report-voyage/confirm-delete-draft`
- select no
- click confirm
- > you should be returned to `your-voyage`
- click `delete`
- select `yes`
- click `confirm`
- > you should be taken to `your-voyages`
- > there should be a console log of the ship name
----
- the ship …
> NMSW-324 Delete draft are you sure routes and skeleton page

- .cypress-cucumber-preprocessorrc.json
- README.md
- cypress.config.js
Configured test to  generate basic html report
Modified scripts to run tests with mailslurp
```
npm run cypress:open:dev --env MAIL_API_KEY=<API_KEY>
```
and select registration.feature
> Add cucumber report

- src/pages/Voyage/VoyageGeneralDeclaration.jsx
- src/pages/Voyage/__tests__/VoyageGeneralDeclaration.test.jsx
NMSW-216
----
Given the system is trying to hit an endpoint
When the auth token is missing or invalid
Then take the user to sign-in page
Given the FE is trying to hit an endpoint that needs a token
When there is not token available
Then the FE redirects the user to the login page
----
- Review the tests and run them
- > They should pass
----
- Currently we do not have forms we cannot test forms being pre-filled.
- We don't have an API endpoint ready to test the functionality so we have mocked the api response in tests
- The code in the browsers will not work and will need to be refactored once the BE is in place
- This will need to be implemented on each handleSubmit for the file uploads once each section is built
> NMSW-216 Auth token missing or invalid

- webpack.config.js
NMSW-375
----
Improve build bundle sizes
----
- delete your dist folder (if you have one)
run npm run build
- in package.json change start to be `"start": "webpack serve --mode production",` (so it runs the production mode)
- run npm start
----
1 - increase size from 244 to 512
2 - add webpack standard chunking
3 - bundle Templates component separately as it's large and rarely changes
> NMSW-375 Add webpack bundling

- webpack.config.js
Revert https://github.com/UKHomeOffice/nmsw-ui/pull/166 changes as they've caused FOUC (flash of unstyled content) issues and we need to find a new fix
> Webpack: revert optimisation changes from PR166

- src/components/DisplayForm.jsx
- src/components/__tests__/DisplayFormTests/DisplayActionButtons.test.jsx
- src/components/__tests__/DisplayFormTests/DisplayFormInputs.test.jsx
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/RegisterEmailResend.jsx
- src/pages/Register/RegisterEmailVerified.jsx
- src/pages/Register/RegisterYourPassword.jsx
NMSW-356
----
Given a submit button has been clicked
And there are no errors (aka form is submitting)
Then the submit button should become disabled
_When a component is waiting on an API call response
Then a loading spinner should show_
The scenario we currently have to test this is the verify email scenario
And the loading spinner only shows when the site is slow
----
- in dev tools, network tab, set your speed to slow 3G
- run app
- go to `/create-account/email-address`
- click `send confirmation email` button
- > page should show errors
- > `send confirmation email` button should remain enabled
- enter valid email addresses
- click `send confirmation email` button
- > you should see the button change to disabled state before the submit completes and the next page loads
- get your link …
> NMSW-356 Disable submit or show loading spinner when processing

- src/constants/AppAPIConstants.js
- src/layout/Nav.jsx
- src/layout/__tests__/Nav.test.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
NMSW-257
----
As a signed in user
I want to sign out
So my session finishes
Given a user has an active authentication token
Then there is a sign out option on the nav bar
Given a user clicks on sign out
Then their session data is cleared (including their auth token)
And a POST is made to /sign-out to blacklist the token
And they are taken to the landing page
----
- sign in
- > you should have a sign out option in the nav
- open dev tools, network tab
- click sign out
- > you should be taken to the sign in page
- > you should have a POST request to the /sign-out endpoint
- open dev tools and check the session
- > there should be no session data for NMSW
----
> NMSW-257 Sign out

- src/components/__tests__/DisplayFormTests/ErrorSpecialRules.test.jsx
- src/components/formFields/__tests__/InputText.test.jsx
- src/utils/Validator.jsx
NMSW-392
----
Fields with phone number validation currently allow you to enter only valid symbols and no numbers.
A number should be required
----
- log in
- go to `your details`
- go to `change your details`
- enter just symbols e.g. `()+`
- click submit
- > you should get an invalid format error
- enter letters
- click submit
- > you should see an error
- enter just numbers
- click submit
- > you should not see an error
- enter numbers and allowed symbols
- click submit
- > you should not see an error
----
Added a test to check input display with type tel as well
> NMSW-392 Require a number in phone number fields

- cypress/support/commands.js
NMSW-408
----
The test user should be deleted after each registration test runs
----
Run Cypress registration tests
----
Discovered endpoint now needs the Bearer token, and it's associated email address in the body of the request
Updated and tests should now pass
> NMSW-408 Cypress: Add body with registered email address to the DELETE user call

- src/constants/AppAPIConstants.js
- src/pages/NavPages/YourVoyages.jsx
- src/pages/NavPages/__tests__/YourVoyages.test.jsx
- src/utils/Auth.js
- src/utils/__tests__/Auth.test.js
NMSW-401
----
Given my token has expired
When I click on report a voyage
Then I am directed to the sign in page
----
- Run the app
- Sign in
- Wait for token to expire (Devops can reduce token expiry time for testing)
- Click on report a voyage
- It should redirect you to the sign in page
- You should not see the token in session storage
----
> NMSW-401 Add case for expired token to the create voyage API call

- src/constants/AppUrlConstants.js
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
- src/pages/Voyage/VoyageGeneralDeclaration.jsx
- src/pages/Voyage/__tests__/VoyageGeneralDeclaration.test.jsx
NMSW-268
----
In preparation for NMSW-268's file uploads for declarations
We need to be able to redirect a user into sign in and back to the voyage page, persisting their declaration id
----
- login
- start a declaration
- delete your token
- click submit button
- > you should be taken to sign in page
- sign in
- > you should be returned to the general declaration upload page
----
> NMSW-268 Pass state in and out of sign in page on redirects

- src/pages/Message/GenericMessage.jsx
- src/pages/Message/__tests__/GenericMessage.test.jsx
NMSW-268
----
Given I have passed state into the Generic Message page
When I click the 'next' link
That state should be passed on to the next page
----
Review and run unit tests as this does not have a UI enabled use case yet (coming in next story)
----
> NMSW-268 Pass state back out of Generic Message if exists

- src/App.jsx
NMSW-387
----
ISSUE
On initial page load, there is a flash of the cookie banner before the main page loads
EXPECTED BEHAVIOUR
Cookie banner should not flash
Cookie banner should only load if no cookie preference is found in browser cookies
----
- Run app
- In the code go to app
- Add `debugger` to the top of the App function
- Return to the app
- Click the arrow a couple of times
- > You should not see a flash of the cookie banner in the steps before the content loads
- Make sure the app works on page refresh AND when the network is set to slow 3G
----
> NMSW-387 Flash of cookie banner on page load

- .eslintrc.json
- src/AppRouter.jsx
- src/constants/AppUrlConstants.js
- src/constants/Config.js
- src/index.js
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/__tests__/RegisterYourDetails.test.jsx
- src/utils/DownloadFile.js
- src/utils/ScrollToTopOnNewPage.jsx
----
While doing a review of linting noticed we have some unneeded rules
----
- run tests
- run cypress tests
- go to `/create-account/your-details`
- > should redirect you to the Try again message
- go through create account process and click validate on your link
- > should should the Your details page
----
- refactored a useEffect so it is not needed and the associated file can be removed : discovered when investigating `"react-hooks/exhaustive-deps": "off",` rule. There is more refactoring to be done so we can reset this back to the 'on' state
- removed some rules that are part of the AirBnB styles by default, we don't need to respecify them here
- We have two special cases where `"import/prefer-default-export": ["off"],` needs to apply, so have removed this rule as a general rule and …
> Remove unneeded linting

- src/components/FileUploadForm.jsx
- src/components/__tests__/FileUploadForm.test.jsx
- src/pages/Voyage/FileUploadConfirmation.jsx
- src/pages/Voyage/VoyageGeneralDeclaration.jsx
- src/pages/Voyage/__tests__/FileUploadConfirmation.test.jsx
- src/pages/Voyage/__tests__/VoyageGeneralDeclaration.test.jsx
NMSW-268
----
Given a user has not uploaded a file
When they click check for errors
Then a form field styled error is shown
Given a user has uploaded a file
When a user clicks check for errors
Then the FE sends a POST to the /declaration/{declarationId}/upload-fal1 endpoint
Given the FE has sent a POST to the /declaration/{declarationId}/upload-fal1 endpoint
When the response is a 200
Then the FE shows the no errors found page
Given the FE has sent a POST to the /declaration/{declarationId}/upload-fal1 endpoint
And the file is not of type .csv or .xlsx
When they click check for errors
Then a form field styled 'invalid type' error is shown
Given the FE has sent a POST to the /declaration/{declarationId}/upload-fal1 endpoint
And the file is missing from the payload
Then a form field styled …
> NMSW-268 File upload for General Declaration FAL 1

- docs/form_creator.md
- src/components/FileUploadForm.jsx
- src/components/MultiFileUploadForm.jsx
- src/components/__tests__/DisplayFormTests/DefaultValuesAndSessionData.test.jsx
- src/components/__tests__/DisplayFormTests/DisplayFormInputs.test.jsx
- src/components/__tests__/DisplayFormTests/ErrorSpecialRules.test.jsx
- src/components/__tests__/FileUploadForm.test.jsx
- src/components/__tests__/MultiFileUploadForm.test.jsx
- src/constants/ErrorMappingFal5.js
- src/pages/NavPages/YourDetails/ChangeYourDetails.jsx
- src/pages/NavPages/YourDetails/ChangeYourPassword.jsx
- src/pages/NavPages/YourDetails/__tests__/ChangeYourDetails.test.jsx
- src/pages/NavPages/YourDetails/__tests__/ChangeYourPassword.test.jsx
- src/pages/Register/RegisterEmailAddress.jsx
- src/pages/Register/RegisterEmailResend.jsx
- src/pages/Register/RegisterYourDetails.jsx
- src/pages/Register/RegisterYourPassword.jsx
- src/pages/Register/__tests__/RegisterEmailAddress.test.jsx
- src/pages/Register/__tests__/RegisterEmailResend.test.jsx
- src/pages/Register/__tests__/RegisterYourDetails.test.jsx
- src/pages/Register/__tests__/RegisterYourPassword.test.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
- src/pages/Voyage/VoyageDeleteDraftCheck.jsx
- src/pages/Voyage/__tests__/VoyageCrew.test.jsx
- src/pages/Voyage/__tests__/VoyageCrewErrorMapping.test.jsx
- src/pages/Voyage/__tests__/VoyageGeneralDeclaration.test.jsx
- src/pages/Voyage/__tests__/VoyagePassengerUpload.test.jsx
NMSW-394
----
UCD has reviewed all error messages and need to update app & tests to match. We're switching to 'harsher' validation error messages. So 'Enter a password that does not contain spaces' is changing to 'Password must not contain spaces'. This is in order to align more closely with COP and E@B error messages.
----
- Open spreadsheet attached to the ticket and scroll down to the current NMSW error messages
- Run app
- Compare the error messages marked as 'incorrect' on the spread sheet to the error messages on the app
- > The error messages in the app should match the new error messages in the table on the spreadsheet
- Check FAL 5 error messages for invalid and max characters (see note below)
----
- **I have had to make changes to the FAL 5 error mapping due to a BE refactor - …
> NMSW-394 Update error messages

- src/components/MultiFileUploadForm.jsx
- src/components/__tests__/MultiFileUploadForm.test.jsx
NMSW-502
----
We send FAL5&6 as one file, and FAL1 as one files - so can allow user to upload up to 8 more files.
----
- Run app
- Sign in
- Click Report a voyage
- Upload a good FAL 1
- Get the the task list page
- Click on supporting documents 
- Select 8 files
- > All 8 files should show in the list
- try to add a 9th file
- You should get max file error
- Refresh the page to clear the errors
- Try to add 9 files
- > You should get max file error
- Refresh the page to clear the errors
- Add a file
- Then try to add another 8 files
- You should get a max file error
----
> NMSW-502 Allow 8 file to be added in supporting documents

- src/pages/Voyage/VoyageDeleteDraftCheck.jsx
- src/pages/Voyage/__tests__/VoyageDeleteDraftCheck.test.jsx
- src/utils/ProtectedRoutes.jsx
NMSW-470
----
Given a user tries to access a protected url
When the user is not signed in
Then they will be directed to the sign in page
When they sign in successfully
Then they will be redirected back to the protected url they tried to access
Given a request is made to a declaration endpoint
When the response indicates the declaration does not belong to the signed in user (404 declaration does not exist)
Then a message of 'declaration does not exist' is shown
----
This impacts all logged in pages, and the entire report voyage journey.
The key scenarios are listed in the Jira ticket.
To check the code changed in this ticket specifically you can
- start a report
- add a bad general declaration file
- click check for errors
- > you should see the error page
- delete your auth token
- click …
> NMSW-470 Redirect protected pages to sign in when no auth token

- src/components/FileUploadForm.jsx
- src/constants/AppAPIConstants.js
- src/constants/ErrorMappingFal5.js
- src/pages/Voyage/__tests__/VoyageCrewErrorMapping.test.jsx
NMSW-522
----
Given I try to upload a blank FAL 5 file
When I click check for errors
Then I am shown a 'Template is empty' error in the error summary
Due to BE changes and after speaking with UCD - blank files should now return a 'Template is empty' error that will show in the error summary on the Crew Details upload page
Also, the wording we get from the BE for certain errors has been changed so we will also need to re-map these errors on the FE
- Blank field errors
- Max character errors
- Invalid character messages
----
- Run app
- Create a voyage
- Get to Crew details FAL 5 upload
- Upload a blank file
- > You should get a 'Template is empty' error in the summary
- Upload a file with invalid characters
- > You should be taken to the error page with invalid character errors
- Click …
> NMSW-522 Update FAL 5 erroring for blank files and field level errors

- src/components/FileUploadForm.jsx
- src/constants/AppAPIConstants.js
- src/constants/ErrorMappingFal5.js
- src/constants/ErrorMappingFal6.js
- src/pages/Voyage/VoyagePassengerUpload.jsx
- src/pages/Voyage/__tests__/VoyageCrewErrorMapping.test.jsx
- src/pages/Voyage/__tests__/VoyagePassengersErrorMapping.test.jsx
NMSW-355
----
Given the fileupload FAL 6 endpoint has returned error messages
When those errors are displayed
The cell reference and error message text should match the table below:
<div class="table-wrap">
Cell | Field | Rule | Error Message
-- | -- | -- | --
A5-99+ | travelDocument | required | Enter P, I or O, or you may enter the full  word: P - Passport, I - ID card - for a national ID card, or O - Other -  for any other document
A5-99+ | travelDocument | wrong value | Enter travel document as P, I, O or as Passport, ID card, Other
B5-99+ | otherTDtype | require value when 'O' or 'Other' was entered in col A | You entered 'Other' as the travel document  type. You must enter the type of travel document, for example SID for  Seafarer's Identity Document
C5-99+ | …
> NMSW-355 Display FAL 6 field level errors

- cypress/e2e/features/check-your-answers-page.feature
- cypress/e2e/features/fal1-upload-general-declaration.feature
- cypress/e2e/features/sign-in.feature
- cypress/e2e/features/task-details-page.feature
- cypress/e2e/features/upload-supporting-documents.feature
- cypress/e2e/pages/file-upload.page.js
- cypress/e2e/pages/task.page.js
- cypress/support/step_definitions/check-your-answers-page.steps.js
- cypress/support/step_definitions/fal1-upload-general-declaration.steps.js
- cypress/support/step_definitions/sign-in.steps.js
- cypress/support/step_definitions/task-page.steps.js
- cypress/support/step_definitions/upload-supporting-documents.steps.js
Test task list feature after FAL5 and 6 upload(NMSW-397)
Test added to cover NMSW-470 -Redirect to signin & back when auth token expires and user is mid way through report creation
Run E2E with
```
```
or
```
```
and select task-details-page.feature
check-your-answers-page.feature
fal1-upload-general-declaration.feature
upload-supporting-documents.feature
> Test nmsw 397

- src/pages/NavPages/YourVoyages.jsx
- src/pages/NavPages/__tests__/YourVoyages.test.jsx
NMSW-531
----
GIVEN a voyage has been started, but has not been submitted
WHEN I view the voyage list
THEN the voyage is displayed as "DRAFT"
----
- Run app
- Sign in
- > If you have reports attached to your account you should see a list of draft reports with a continue button next to each
- > You should not see reports that do not have a FAL 1 attached (reports in the list without ship name, voyage type or a date)
- Click on continue
- > You should be taken to the task list page for that voyage (only for drafts)
- Go back to the your voyages page
- Delete your token and refresh
- > You should be taken to the sign in page
----
- We have removed the filtering for MVP - new design has been okayed by UCD team
- We only get draft reports from the BE so only voyages with the status of draft …
> NMSW-531 Display draft voyages

- src/pages/SignIn/ResendRequestPasswordReset.jsx
- src/pages/SignIn/__tests__/RequestPasswordResetConfirmation.test.jsx
- src/pages/SignIn/__tests__/ResendRequestPasswordReset.test.jsx
----
Given I have entered a registered and validated email address
When I click submit
Then I should be shown the confirmation page
And I should receive a password reset email
Given I click 'not received an email' on the confirmation page
Then I should be taken to the request a new link page
**Given I click request a new link on the confirmation page
When the stored email address is a registered and validated one
Then I should be shown the confirmation page
And I should receive a password reset email**
**Given I click change where the email was sent on the confirmation page
And I enter a registered and validated email address in the field
When I click request a new link
Then I should be shown the confirmation page
And I should receive a password reset email**
**Given I enter an email …
> NMSW-203 Forgotten password, send for a different email

- src/pages/Voyage/VoyageCheckYourAnswers.jsx
- src/pages/Voyage/VoyageTaskList.jsx
- src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx
- src/pages/Voyage/__tests__/VoyageTaskList.test.jsx
NMSW-554
----
We now receive FAL 5 and 6 data as a list of objects which means that the code for NMSW-424 and NMSW-154) is no longer working as expected.
FE code that needs updating:
- Tasklist page: Make sure that the statuses are updating as expected for FAL 5 and 6 uploads
- CYA page: Make sure the page loads and displays the filename and has a link with the ability to download the file as expected
----
- Follow test steps for https://github.com/UKHomeOffice/nmsw-ui/pull/312
- Follow test steps for https://github.com/UKHomeOffice/nmsw-ui/pull/313
----
> NMSW-554 Update FE code to accommodate BE changes to how we receive FAL data

- src/components/ConfirmationMessage.jsx
- src/constants/AppConstants.js
- src/pages/Voyage/VoyageCheckYourAnswers.jsx
- src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx
NMSW-244
----
Given I have completed all required inputs
And I am on the Check Your Answers page
And my declaration status is draft
When I click 'submit'
Then a PATCH request is sent to /declarations with a status of PreSubmitted'
> from here the backend takes over with the submission to CBP and the sending of emails to the user/support as required
----
- go to the CYA page
- click submit
- > you should see the confirmation page
- > you should see in network tab a PATCH request for that declaration with a PreSubmitted status
----
Added the standard handling of 422/401/500 responses from the PATCH
We only have 'draft' status declarations at the moment - different buttons/functions will be added for submitted status (cancel / handleCancel), and no button/function if …
> NMSW-244 Submit a declaration

- package-lock.json
- webpack.config.js
NMSW-561
----
- npm audit reporting webpack needs an update with audit fix
- prod build asset initial bundle now at 600, increase to 1000 allowed for MVP
----
- run tests
- run app in prod mode
Things should load and not error out due to size
----
- we have a ticket in the backlog to investigate initial bundle size and see if we can reduce it
> NMSW-561 Webpack update

- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.test.jsx
NMSW-204
----
Given a user has registered but not verified their email
When they submit the sign in form
Then they are shown an info page asking them to verify their email
_Note: we had two other implementations of handling this scenario which are removed as part of this PR as once this new UX was designed for the forgotten password flow it was decided to use the same UX for sign in_
----
- register an email address
- go to sign in
- try to sign in with that email and any password
- > you should see the 'you need to verify' page
----
> Replace sign in unverified flow

- src/components/FileUploadForm.jsx
- src/components/__tests__/FileUploadForm.test.jsx
- src/constants/AppAPIConstants.js
----
Given I have uploaded a FAL5 form
When I attempt to upload a FAL6 form that has a record that contains the same travel_document_id and country as a record on the FAL5 form
Then I am shown an error
Given I am uploading a FAL5 form
When I attempt to upload a FAL5 form that has two or more records that contain the same travel document id and country
Then I am shown an error
Given I am uploading a FAL6 form
When I attempt to upload a FAL6 form that has two or more records that contain the same travel document id and country
Then I am shown an error
----
Scenario one
- create a FAL5 and FAL6 form where at least one row on each has the same travel document number and country
- upload the FAL5 form
- upload the FAL6 form
- > you should see an error
Scenario two
- …
> NMSW-552 Handle duplicate records between FAL5 and FAL6 errors

- src/components/StatusTag.jsx
- src/constants/AppConstants.js
- src/pages/NavPages/YourVoyages.jsx
- src/pages/NavPages/__tests__/YourVoyages.test.jsx
- src/pages/Voyage/VoyageTaskList.jsx
----
We're using status tags across a few files now so add a status tag component and refactor existing places to use it
----
- view Your voyages
- > draft tags should appear as before
- add a FAL1
- > task details page should show the completed, required, optional, and cannot start tags as before
- add a FAL5 and select no for passengers
- > CYA should now show a not started tag as before
----
Not all statuses are used on a page yet so some are currently untestable in the UI but I've added them here in preparation for future PRs
> NMSW-538 Add status tag component and refactor to use it

- src/components/MultiFileUploadForm.jsx
- src/components/__tests__/MultiFileUploadForm.test.jsx
NMSW-514 (pt 2 now that BE is working)
----
A bug was found where if you upload a file, then delete that file, you see two instances of that file. This was because the files in 'limbo' state (uploaded but were not retrieved from the initial GET call) are still a part of the filesAddedForUpload array but on calling the getDeclarationData again, they also become a part of the supportingDocumentsList so they appear twice. This code does this by filtering files with a pending tag so that these do not disappear is you delete an uploaded file in it's 'limbo' state
----
Scenario 1: Deleting previously uploaded file 
- Run app
- Sign in
- Create a voyage declaration
- Get to supporting docs section
- Upload a couple of files
- Refresh the page
- Delete one of the files
- > It should be removed …
> NMSW-514 Delete supporting docs pt 2

- src/pages/NavPages/YourVoyages.jsx
- src/pages/NavPages/__tests__/YourVoyages.test.jsx
- src/pages/Voyage/VoyageDeleteDraftCheck.jsx
- src/pages/Voyage/__tests__/VoyageDeleteDraftCheck.test.jsx
----
GIVEN a declaration is a draft (has not yet been submitted)
WHEN the user deletes the declaration
THEN it no longer appears in the voyage list
----
- load your voyages page
- > there should be no notification banner
- go to a report
- click delete
- click yes
- click submit [note not actually deleting at the moment]
- > you should be returned to your voyages page
- > you should see a notification banner confirming you deleted that ships draft
- refresh the page
- > there should be no notification banner
----
Endpoint not yet available so this will fail in the browser
> NMSW-546 Delete a draft report

- src/pages/NavPages/YourVoyages.jsx
- src/pages/NavPages/__tests__/YourVoyages.test.jsx
NMSW-245
----
If a voyage is in draft status and does not have general declaration details then we send a delete request for it 
----
- Run app
- Sign in
- Go to Your voyages
- You should only see declarations with General declarations attached
- Open network tab
- Create a declaration (do not upload general declaration)
- Go back to your voyages
- You should see a successful delete request for the declaration you just created
----
- I opened this as a draft because the delete request was running twice and one was failing as the declaration no longer existed - this has now been resolved by jennikate so I have also reviewed her changes
> NMSW-245 On GET drafts delete any without general declarations

- src/components/FileUploadForm.jsx
- src/components/__tests__/FileUploadForm.test.jsx
- src/constants/AppAPIConstants.js
----
Error wording was updated in API as part of the overhaul of error messaging
We still need to catch this particular error in front end as we display it as a form error, not the error list page error
----
You will need
- a FAL 5 where two or more rows have the same document number and country
- a FAL 6 where two or more rows have the same document number and country
- a FAL 5 which has all unique rows
- a FAL 6 which has all unique rows within the file, however at least one of the rows should have the same document number and country as a row on the unique FAL 5 document
- upload a FAL 5 where two or more rows have the same document number and country
- > you should see the error `Details listed on this file are not allowed, because they're the same as details …
> NMSW-552 Remap errors as wording has changed from API

- cypress/e2e/features/landing-page.feature
- cypress/support/step_definitions/landing-page.steps.js
Test added for [NMSW-162] help page
Test added to verify footer links
```
```
Select landing-page.feature
> Test NMSW-162 help page feature and footer links

- src/pages/Voyage/VoyageCheckYourAnswers.jsx
- src/pages/Voyage/VoyageCheckYourAnswers/VoyageCancelConfirmation.jsx
- src/pages/Voyage/__tests__/VoyageCheckYourAnswers.test.jsx
----
Given I have submitted a declaration previously
When I click cancel
Then I am asked are you sure
When I select no and click confirm
Then I am returned to the CYA page
When I select yes and click confirm
Then a request to PATCH status to `PreCancelled` is sent
Then I am taken to `your voyages` and shown a confirmation of cancellation banner
Then I can no longer see that report in my list
----
- create and submit a declaration
- return to the declaration (check your answer page)
- click cancel
- select 'no' and click confirm when asked are you sure
- > you should be returned to the CYA page
- > your declaration should still exist
- click cancel
- select 'yes' and click confirm
- > you should be taken to your voyages with a confirmation of deletion banner
- > you should not see that …
> NMSW-337 Set a declaration to PreCancelled

- src/constants/AppAPIConstants.js
- src/pages/NavPages/YourDetails/YourDetails.jsx
- src/pages/NavPages/YourDetails/__tests__/YourDetails.test.jsx
----
Given I am a registered & active user
When I go to the your details page
Then I can see my company type
----
_you may need to register a new user if your user account is old as some models were changed a while back_
- register a user as a Shipping Agent
- go to your details page
- you should see company type as 'Shipping agent'
- register a user as Other
- go to your details page
- you should see company type as 'Other'
----
company name is not available in the dataset at the moment so has been hidden from the UI
> NMSW-551 Add group details to your details page

- cypress/e2e/features/your-details-page.feature
- cypress/e2e/pages/registration/password.page.js
- cypress/support/step_definitions/your-details-page.steps.js
Added test for NMSW-547 Display user details
```
```
and select your-details-page.feature
> Test NMSW-547 Display user details

- cypress/e2e/features/upload-supporting-documents.feature
- cypress/e2e/pages/file-upload.page.js
- cypress/support/step_definitions/upload-supporting-documents.steps.js
- Added test for NMSW-243 Display uploaded supporting documents
- Added test for NMSW-514 Delete uploaded supporting documents
```
```
and select upload-supporting-documents.feature
> Test display supporting document upload with delete feature

- cypress/e2e/features/sign-in.feature
- cypress/e2e/pages/registration/password.page.js
- cypress/fixtures/registration.json
Test added for NMSW-551 -Display your group details
Changed sign-in credentials to work with the changes
```
```
select your-details-page.feature
> Test NMSW-551 -Display your group details

- cypress/e2e/features/fal1-upload-general-declaration.feature
- cypress/fixtures/registration.json
- cypress/support/step_definitions/fal1-upload-general-declaration.steps.js
- cypress/support/step_definitions/sign-in.steps.js
Test added for NMSW-245 On GET drafts delete any without general declarations
----
```
```
Select fal1-upload-general-declaration.feature
> Test NMSW-245 On GET drafts delete any without general declarations

- src/pages/NavPages/YourVoyages/YourVoyages.jsx
- src/pages/NavPages/YourVoyages/__tests__/YourVoyages.test.jsx
- src/utils/API/handleAuthErrors.js
- src/utils/API/useGetAllDeclarations.jsx
NMSW-589
----
Refactor api functions to reduce repetition / improve maintenance and readability
- refactor get all declarations for a user out of the your voyages page
- create a handler for Auth error responses from an API call so we only have to manage the redirects to sign in etc. in one place in future (will move other functions to using the handler in separate PRs)
----
- check you see all your voyages when logged in
- check that if you create a declaration but don't upload a general dec form that when you return to your voyages page it is deleted
- check that if you remove your auth token and try to load your voyages page you're redirected to sign in
----
> NMSW-589 Refactor getting all declarations calls/error handling

- src/assets/main.scss
- src/components/Pagination/Pagination.jsx
- src/components/Pagination/__tests__/PaginationClick.test.jsx
- src/components/Pagination/__tests__/PaginationSetup.test.jsx
- src/components/Pagination/calculatePaginationNextPageNumber.jsx
- src/components/Pagination/createPaginationArray.js
- src/constants/AppConstants.js
- src/layout/Nav.jsx
- src/pages/NavPages/YourVoyages/YourVoyages.jsx
- src/pages/NavPages/YourVoyages/YourVoyagesDisplay.jsx
- src/pages/NavPages/YourVoyages/__tests__/YourVoyages.test.jsx
- src/utils/API/useGetAllDeclarations.jsx
NMSW-618 (FE) of NMSW-611
----
GIVEN there are less than 100 records for the user
WHEN they view the pagination section
THEN only page 1 is shown
GIVEN there are more than 100 records for the user
WHEN the result displayed
THEN there 100 records per page
AND a page link for each 100 records
GIVEN there is at least one voyage (of any status)
WHEN you are viewing page 1
THEN the 'Previous' link is hidden
GIVEN you are viewing the last page
THEN the 'next' link is hidden
GIVEN the voyages are displayed as paginated pages
WHEN there are more than 3 pages
THEN page 1 is always shown
AND the last page number is always shown
AND the page number I am on is shown
AND the page numbers to the left and right of the page I am on are shown
AND ellipses replace in any missing page numbers
GIVEN I am …
> NMSW-611 Pagination

- src/App.test.jsx
- src/pages/Landing/Landing.jsx
- src/pages/Landing/Landing.test.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/__tests__/SignIn.test.jsx
----
- remove 'create account' link from sign in page
- enable user going directly to `/create-account/email-address`
----
- go to `/create-account/email-address` you should get the create account page
- > you should be able to sign up
- go to sign in page
- > there should be no create account link
----
> NMSW-856 Remove link to create account, enable direct URL to create account

- src/constants/AppAPIConstants.js
- src/pages/NavPages/YourDetails/YourDetails.jsx
- src/pages/NavPages/YourDetails/__tests__/YourDetails.test.jsx
- src/pages/SignIn/RequestPasswordReset.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/__tests__/RequestPasswordReset.test.jsx
- src/pages/SignIn/__tests__/SignIn.test.jsx
NMSW-869
----
There has been a service update so some users will need to change their password to update their account. This ticket is to make the flow easier to follow to allow users to access their accounts again.
----
- Run app
- Ask Adèle for details of an account that needs updating
- Try to sign in
- > You should be taken to a message page with a service update
- Click the link 
- > You should be taken to the password reset page with a title of 'Reset password' (don't actually change the password though!)
----
> NMSW-869 Handle password reset to update user account

- src/layout/Nav.jsx
- src/layout/__tests__/Nav.test.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/__tests__/SignIn.test.jsx
- src/utils/Auth.js
NMSW-863
----
Given I am signed in
When I click the sign out link
Then I am signed out
And I see the sign in page
Given a user clicks the sign out link
Then we post/patch to the sign out end point passing the refresh token
And we clear all session data
And we redirect them to the sign in page
----
- Run app
- Sign in public account
- Open dev tools -> application
- > You should see a refresh token stored
- Open the network tab in dev tools
- Click sign out
- > You should see a successful call to the sign out endpoint
- > You should be redirected to /sign-in
- Open dev tools -> application
- > You should not see anything stored in session
- Sign in again
- Open dev tools -> application
- Delete your refresh token
- Open the network tab in dev tools
- Click sign out
- > You should see an …
> NMSW-863 Update sign out

- src/constants/AppAPIConstants.js
- src/pages/SignIn/RequestPasswordReset.jsx
- src/pages/SignIn/__tests__/RequestPasswordReset.test.jsx
NMSW-997
----
Unlike NMSW-internal when try to click forgotten email link and enter an unverified email address, we are not taking user to email address has not been verified page. Instead we directly redirect them to check your email page.
This is because the BE response for an email that has not been verified as been updated. Therefore we need to update the FE mapping to match what is returned from the BE
----
- Run app
- Create an account that is registered but not verified (do not complete registration process)
- Click on forgotten your passowrd
- Enter the email of the unverified email
- > You should be taken to the email is not verified page
----
- If you click on the send confirmation email click on the email not verified page no invitation will be resent - this is because we …
> Update FE mapping for user not verified error

- .drone.yml
- cypress.config.js
Changed env name for mailslurp Api Key
To Run E2E tests
```
npm run cypress:run:staging
```
> Change env name for mailslurp Api Key
